{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.76",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.76.jar",
          "url": "core-ai-1.1.76.jar",
          "size": 422032,
          "sha512": "b24f94f85b740c07197010bb870285ead209f906ba283b01b1ededbc09ae3c934f07a430284952ece349e6bc08bc4f0c7bd0cfa185ad159fce5fe314018f4de2",
          "sha256": "eb84d5e5048e85a1a09e1715a4e310fac27751b38e55023e74824aa6949640b5",
          "sha1": "dcf2919887cbf4514d13a17ea93768724bc279e0",
          "md5": "f8622ee0169deea70a681c2884c55796"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.76.jar",
          "url": "core-ai-1.1.76.jar",
          "size": 422032,
          "sha512": "b24f94f85b740c07197010bb870285ead209f906ba283b01b1ededbc09ae3c934f07a430284952ece349e6bc08bc4f0c7bd0cfa185ad159fce5fe314018f4de2",
          "sha256": "eb84d5e5048e85a1a09e1715a4e310fac27751b38e55023e74824aa6949640b5",
          "sha1": "dcf2919887cbf4514d13a17ea93768724bc279e0",
          "md5": "f8622ee0169deea70a681c2884c55796"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.76-sources.jar",
          "url": "core-ai-1.1.76-sources.jar",
          "size": 175748,
          "sha512": "91e8a73a8be5a96361a09abf37947e8f7a744a83ce32ffa7cdb67828f9fb1296113c5f549b0c3bd201af58544b297992dd8af74d4ef39129e6db9286f17beb19",
          "sha256": "7a84d75b9f5afd1bb8f38139023af058f9ee7d9bda8f22709c67767c3d8d3ae9",
          "sha1": "2e79ebdcc9983fd40a9f9b6b444f5ad51cfcc94f",
          "md5": "884e9bd0752f053e6ac7254eb6adfa85"
        }
      ]
    }
  ]
}
