{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.114.jar",
          "url": "core-ai-1.1.114.jar",
          "size": 719827,
          "sha512": "564e4c9c59d5cd4680079e15b9cc9636cd745188e6daf28aab0aada2e8dbc86ea17e01331f72b34c6189367d5a121479cbc2c9bf2a3b475304bdb4cb9a56d17b",
          "sha256": "eb757b77a40c8708a2b9c4be04ed39d51cc009722630472591255537ba951e30",
          "sha1": "aebd439ef14b1b0c996b46162643eab2e7373c29",
          "md5": "c992e4c91ba5b144623f1984c167d114"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.114.jar",
          "url": "core-ai-1.1.114.jar",
          "size": 719827,
          "sha512": "564e4c9c59d5cd4680079e15b9cc9636cd745188e6daf28aab0aada2e8dbc86ea17e01331f72b34c6189367d5a121479cbc2c9bf2a3b475304bdb4cb9a56d17b",
          "sha256": "eb757b77a40c8708a2b9c4be04ed39d51cc009722630472591255537ba951e30",
          "sha1": "aebd439ef14b1b0c996b46162643eab2e7373c29",
          "md5": "c992e4c91ba5b144623f1984c167d114"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.114-sources.jar",
          "url": "core-ai-1.1.114-sources.jar",
          "size": 340294,
          "sha512": "30852358b470cc61adc49b75ff2ea52512a77daba549a102103f94ae50eb54bebec57f4cc3f69e67ada31caae8d88617d383708c308867b31eb4b1cc5b798dbe",
          "sha256": "2bcb417b50b3dc8b983d707a7f2c896405d3896adb5aa04968736d4d8b6bb6a1",
          "sha1": "b671e643655464858b8a3a430b1316e79151fbee",
          "md5": "764dab521005a235fabc6ff0c3e3cafc"
        }
      ]
    }
  ]
}
