{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 346208,
          "sha512": "085ca108bcdf76d8dece17edaaa847daa523f202ac45239093d510cb05bf55ac21150775efd733fa752393ef087c74e240e6f2baccbc0834097b648d92193835",
          "sha256": "c5fca60f5c9fe557d0887f600151e4828b6b1e4e47ab9a5576dd62b2f156b2cb",
          "sha1": "0934b6f731822cacc889467a2921d04e3cbc753a",
          "md5": "e0fbeb3b506c7675c6c125c532750d51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 346208,
          "sha512": "085ca108bcdf76d8dece17edaaa847daa523f202ac45239093d510cb05bf55ac21150775efd733fa752393ef087c74e240e6f2baccbc0834097b648d92193835",
          "sha256": "c5fca60f5c9fe557d0887f600151e4828b6b1e4e47ab9a5576dd62b2f156b2cb",
          "sha1": "0934b6f731822cacc889467a2921d04e3cbc753a",
          "md5": "e0fbeb3b506c7675c6c125c532750d51"
        }
      ]
    }
  ]
}
