{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 327594,
          "sha512": "242cc90792fb30bf23841ce00a62e65fcbda672feb3b4f69b4986c359ee789b8687b14fd5a7691caa15b4e8ba135b516a8be3cc6cbc3003a20de5d3c14e24b24",
          "sha256": "a088c71eea7d3c064b9bfb04cb8aff05a29bf75f2f0a9ea637aa8c2358f0d908",
          "sha1": "1010ed03bcb0b2487c7aa3b512f3654c72bf36cc",
          "md5": "1fae2e14fc76bba496ad2252d322ac63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 327594,
          "sha512": "242cc90792fb30bf23841ce00a62e65fcbda672feb3b4f69b4986c359ee789b8687b14fd5a7691caa15b4e8ba135b516a8be3cc6cbc3003a20de5d3c14e24b24",
          "sha256": "a088c71eea7d3c064b9bfb04cb8aff05a29bf75f2f0a9ea637aa8c2358f0d908",
          "sha1": "1010ed03bcb0b2487c7aa3b512f3654c72bf36cc",
          "md5": "1fae2e14fc76bba496ad2252d322ac63"
        }
      ]
    }
  ]
}
