{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 214247,
          "sha512": "5a99ad9098b84c899c432c6bc5272f7868446fdaf65320b7339613433770bf5d49daf72db87c72bd7e8d671a7860f60ca1f1791c5217040e5c2cc3638e83cf62",
          "sha256": "ac439343db4d4a50e0830f3fbe1e1441661f1a3bd137bc94f917662950367133",
          "sha1": "b5080c2ab76200d59ab07ab5de4887d54e24827a",
          "md5": "9371e0e18a222ba8554085031530e439"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 214247,
          "sha512": "5a99ad9098b84c899c432c6bc5272f7868446fdaf65320b7339613433770bf5d49daf72db87c72bd7e8d671a7860f60ca1f1791c5217040e5c2cc3638e83cf62",
          "sha256": "ac439343db4d4a50e0830f3fbe1e1441661f1a3bd137bc94f917662950367133",
          "sha1": "b5080c2ab76200d59ab07ab5de4887d54e24827a",
          "md5": "9371e0e18a222ba8554085031530e439"
        }
      ]
    }
  ]
}
