{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 182265,
          "sha512": "0ef881b8817d77eb181e9226ccedc5877a2c01f10a1f953b95db6ec2dba9ed11193ecc7963b6e94ba964d8b132edfbf8eb6bfadd2ad63bdc7c8dab54ccc832a9",
          "sha256": "f3dfd26891572e964d6150bbae1e047457f18c41540eb93bee9b564f761285ad",
          "sha1": "5773425f369d9423a7cb5fa7013024d2505a21e6",
          "md5": "fb03b61e3b05834fcca258f045ef4e69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.theokanning.openai-gpt3-java",
          "module": "client",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "io.modelcontextprotocol",
          "module": "kotlin-sdk",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 182265,
          "sha512": "0ef881b8817d77eb181e9226ccedc5877a2c01f10a1f953b95db6ec2dba9ed11193ecc7963b6e94ba964d8b132edfbf8eb6bfadd2ad63bdc7c8dab54ccc832a9",
          "sha256": "f3dfd26891572e964d6150bbae1e047457f18c41540eb93bee9b564f761285ad",
          "sha1": "5773425f369d9423a7cb5fa7013024d2505a21e6",
          "md5": "fb03b61e3b05834fcca258f045ef4e69"
        }
      ]
    }
  ]
}
