{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 190219,
          "sha512": "ba8de3a051653a5fa9a61120a759011ea0ae1a256a1e26c38837d677623b665013cce9de8ce9166ac4608d67e8ba6ba4c9eb638ef2b109cd8548ed7d37622594",
          "sha256": "cc2f036d08d73a38bb7089e54b30024bd3f021f4ecf123c084dac5f6bcb82262",
          "sha1": "ed835fb698c35562e92d94a81e5e6b03db8d8996",
          "md5": "374ebaea6eeca52691d1fea31d17aec5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.theokanning.openai-gpt3-java",
          "module": "client",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.3"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "io.modelcontextprotocol",
          "module": "kotlin-sdk",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-1.0.0-SNAPSHOT.jar",
          "size": 190219,
          "sha512": "ba8de3a051653a5fa9a61120a759011ea0ae1a256a1e26c38837d677623b665013cce9de8ce9166ac4608d67e8ba6ba4c9eb638ef2b109cd8548ed7d37622594",
          "sha256": "cc2f036d08d73a38bb7089e54b30024bd3f021f4ecf123c084dac5f6bcb82262",
          "sha1": "ed835fb698c35562e92d94a81e5e6b03db8d8996",
          "md5": "374ebaea6eeca52691d1fea31d17aec5"
        }
      ]
    }
  ]
}
