{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.52.jar",
          "url": "core-ai-1.1.52.jar",
          "size": 387379,
          "sha512": "1ef0bdbe2b8c06ae3911fd6a5f5c023c560bc0c52e4018ea0b29b41bd3bfb483f14521a71c3fcb9eb9bede58290d8ab5acde73178941df143d837bc43d680818",
          "sha256": "56202f8ec7672a308f3236f98d0fc02897b15e32dd7a86843f153a3d020794a0",
          "sha1": "29dc03b0052792061d6a788344c6ebe8c5493f0a",
          "md5": "87a56856542886b6b020c2043f24b5c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.11"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.52.jar",
          "url": "core-ai-1.1.52.jar",
          "size": 387379,
          "sha512": "1ef0bdbe2b8c06ae3911fd6a5f5c023c560bc0c52e4018ea0b29b41bd3bfb483f14521a71c3fcb9eb9bede58290d8ab5acde73178941df143d837bc43d680818",
          "sha256": "56202f8ec7672a308f3236f98d0fc02897b15e32dd7a86843f153a3d020794a0",
          "sha1": "29dc03b0052792061d6a788344c6ebe8c5493f0a",
          "md5": "87a56856542886b6b020c2043f24b5c7"
        }
      ]
    }
  ]
}
