{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.1.1.jar",
          "url": "litellm-library-1.1.1.jar",
          "size": 27269,
          "sha512": "a97fba292f89365d2e4f17740435dc5f872d10b6f52d6566f267764c22e0355841e43f54d1dd831551cf0e3d5d7bff8332b8975d23427ab9df1762609fd30233",
          "sha256": "df6713aabccb0780dd15aea77f75eb857271ff7141f358775d5d764ad03f987a",
          "sha1": "ed99537d490380a25db1cd395f6f52d409ba9c81",
          "md5": "77c75ff67af37db917da589b7f7b79ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.1.1.jar",
          "url": "litellm-library-1.1.1.jar",
          "size": 27269,
          "sha512": "a97fba292f89365d2e4f17740435dc5f872d10b6f52d6566f267764c22e0355841e43f54d1dd831551cf0e3d5d7bff8332b8975d23427ab9df1762609fd30233",
          "sha256": "df6713aabccb0780dd15aea77f75eb857271ff7141f358775d5d764ad03f987a",
          "sha1": "ed99537d490380a25db1cd395f6f52d409ba9c81",
          "md5": "77c75ff67af37db917da589b7f7b79ba"
        }
      ]
    }
  ]
}
