{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.80",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.80.jar",
          "url": "core-ai-1.1.80.jar",
          "size": 416938,
          "sha512": "beafa41c40aa975da774e6b8ac3b51b1d23c612a19bc9d2535e1d593a85897387f3e0ce542d7e25ac94b9a82ecb021f41dfd41a1309a65f5ecd6cafc957c2988",
          "sha256": "641e4b5d45d718afc3a997116d30730eb2e405b75451732c1d72dc641ee53483",
          "sha1": "48fe994112e0a38a81ef80257e693f46dea53c4a",
          "md5": "1a01f83ade3cad5b7306138f232800ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.80.jar",
          "url": "core-ai-1.1.80.jar",
          "size": 416938,
          "sha512": "beafa41c40aa975da774e6b8ac3b51b1d23c612a19bc9d2535e1d593a85897387f3e0ce542d7e25ac94b9a82ecb021f41dfd41a1309a65f5ecd6cafc957c2988",
          "sha256": "641e4b5d45d718afc3a997116d30730eb2e405b75451732c1d72dc641ee53483",
          "sha1": "48fe994112e0a38a81ef80257e693f46dea53c4a",
          "md5": "1a01f83ade3cad5b7306138f232800ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.80-sources.jar",
          "url": "core-ai-1.1.80-sources.jar",
          "size": 175007,
          "sha512": "260b3886a3a3a598d6f8ede39c69f5639acc29108bf193f5490750a2ce40592852066a2be3ff40f13e031ac2b96f6dec673c7aec24fad2c28d585a0a2ae8c22a",
          "sha256": "2b47c8f020ea8e75850aa19d790562d941bc03795c21b8058b824dc1e3c5257c",
          "sha1": "3aa0064c083e953b764fb8296d6185074316db2d",
          "md5": "6f2e88fb3d0378de9003c91fac4432c2"
        }
      ]
    }
  ]
}
