{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.10.jar",
          "url": "core-ai-1.1.10.jar",
          "size": 376104,
          "sha512": "83dff102002a2302fab3e4c43c5093f8117592339f398860755c757995c4f75f22a512a94f0f08d12ad30384b3a65bf73f9229c2f938449e079862535bb82585",
          "sha256": "161e788264bbe0c2520a0d74552609a7ae7c07cf7923a1a68fd3febdae72dfbe",
          "sha1": "06226e6cca7aac5d585acd2ab062b1e6f873ee6f",
          "md5": "cc91b8bb747ba94b183dce14cdd42f95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.10.jar",
          "url": "core-ai-1.1.10.jar",
          "size": 376104,
          "sha512": "83dff102002a2302fab3e4c43c5093f8117592339f398860755c757995c4f75f22a512a94f0f08d12ad30384b3a65bf73f9229c2f938449e079862535bb82585",
          "sha256": "161e788264bbe0c2520a0d74552609a7ae7c07cf7923a1a68fd3febdae72dfbe",
          "sha1": "06226e6cca7aac5d585acd2ab062b1e6f873ee6f",
          "md5": "cc91b8bb747ba94b183dce14cdd42f95"
        }
      ]
    }
  ]
}
