{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.58.jar",
          "url": "core-ai-1.1.58.jar",
          "size": 381051,
          "sha512": "732d1371ba2e9eaff7713e4a9c95a1e2bff379c2ed02b631886b8e118b5ff9085fdd0f440ec406cf13f9b387cf598134fac30c8e4beee1973c67c7947c4e0c54",
          "sha256": "faa9dcf960f486ef44fa9f878d9a92c9842a6dee697ebc644c5d05db4b7cc1ba",
          "sha1": "4a8cb1c8e4c410fe28a34d12eccc96841732ba08",
          "md5": "a16510197329a2112e74212a551f82b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.58.jar",
          "url": "core-ai-1.1.58.jar",
          "size": 381051,
          "sha512": "732d1371ba2e9eaff7713e4a9c95a1e2bff379c2ed02b631886b8e118b5ff9085fdd0f440ec406cf13f9b387cf598134fac30c8e4beee1973c67c7947c4e0c54",
          "sha256": "faa9dcf960f486ef44fa9f878d9a92c9842a6dee697ebc644c5d05db4b7cc1ba",
          "sha1": "4a8cb1c8e4c410fe28a34d12eccc96841732ba08",
          "md5": "a16510197329a2112e74212a551f82b9"
        }
      ]
    }
  ]
}
