{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.1.5.jar",
          "url": "litellm-library-1.1.5.jar",
          "size": 27120,
          "sha512": "061e91ea4ea416d1becc4ac336576cf7ca1e1f5e5bbb51e9607356b6cb64a3ab31024af5e91444d58dd672d5cf6d515f788e68dc9ca1271fbfff7cf1c670cfd5",
          "sha256": "407c9bc2b0ca2b407474bcec2d0546bc2b29bfabc9845ca51ff656837dad191a",
          "sha1": "9c474baff79a3b774e9a1bc27682cb9b0e0934f0",
          "md5": "5b6783ac962d4446831182a32e62aa47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.1.5.jar",
          "url": "litellm-library-1.1.5.jar",
          "size": 27120,
          "sha512": "061e91ea4ea416d1becc4ac336576cf7ca1e1f5e5bbb51e9607356b6cb64a3ab31024af5e91444d58dd672d5cf6d515f788e68dc9ca1271fbfff7cf1c670cfd5",
          "sha256": "407c9bc2b0ca2b407474bcec2d0546bc2b29bfabc9845ca51ff656837dad191a",
          "sha1": "9c474baff79a3b774e9a1bc27682cb9b0e0934f0",
          "md5": "5b6783ac962d4446831182a32e62aa47"
        }
      ]
    }
  ]
}
