{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.110",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.110.jar",
          "url": "core-ai-1.1.110.jar",
          "size": 713957,
          "sha512": "dda5b5c3afad224fc85f5d0f797ffa33b75cf42ad118a7d5b63bb19b7eb96d3428d982fc4e8a21ac4f55381934d02cc2d03ddcde23cad241c851d5567aaf2827",
          "sha256": "d4bb789f14e85fd4b491a6272fc69b13570b743e756e11527e9c14a48d922bc1",
          "sha1": "895e098ec667af8c5e2b45ef4895d1b32f93e496",
          "md5": "e1d685bd663fbb1c379c98f4fbd5bae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.110.jar",
          "url": "core-ai-1.1.110.jar",
          "size": 713957,
          "sha512": "dda5b5c3afad224fc85f5d0f797ffa33b75cf42ad118a7d5b63bb19b7eb96d3428d982fc4e8a21ac4f55381934d02cc2d03ddcde23cad241c851d5567aaf2827",
          "sha256": "d4bb789f14e85fd4b491a6272fc69b13570b743e756e11527e9c14a48d922bc1",
          "sha1": "895e098ec667af8c5e2b45ef4895d1b32f93e496",
          "md5": "e1d685bd663fbb1c379c98f4fbd5bae6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.110-sources.jar",
          "url": "core-ai-1.1.110-sources.jar",
          "size": 337363,
          "sha512": "c46b85e3286f13401fb68463b88978f3e463b8d13c9e3be94b16f5757e914367766af6c0cbd30a1d341baef281c04d50bcb05bb59c35b52efafe06802c6fca18",
          "sha256": "d159bbc684dea2eecf0dc382b3f1a793cda59ded853ebb442ccfa50ee63a5499",
          "sha1": "5d5d206d541a965dbaae71b0ee5ffd9b9161cbcf",
          "md5": "9a629b5da598491e6b6de71dea4e28d7"
        }
      ]
    }
  ]
}
