{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.71.jar",
          "url": "core-ai-1.1.71.jar",
          "size": 417411,
          "sha512": "c4f8de8e088ebd3dbcdf13e13acae22df0ce5a0f0acd32b81c81a4dcbf6ee75504b67267e16bdcece0071aa419e6ec604144a4f64f1db6161636437c00597a81",
          "sha256": "ad37504e7e518819e1760454406694f324d97b7e3b4ec9d2845268ab884c0dea",
          "sha1": "4601fdbe1f5c47e369713147b4274aa7c91423dd",
          "md5": "0f24e53233db3d5df836e3d2909e0040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.71.jar",
          "url": "core-ai-1.1.71.jar",
          "size": 417411,
          "sha512": "c4f8de8e088ebd3dbcdf13e13acae22df0ce5a0f0acd32b81c81a4dcbf6ee75504b67267e16bdcece0071aa419e6ec604144a4f64f1db6161636437c00597a81",
          "sha256": "ad37504e7e518819e1760454406694f324d97b7e3b4ec9d2845268ab884c0dea",
          "sha1": "4601fdbe1f5c47e369713147b4274aa7c91423dd",
          "md5": "0f24e53233db3d5df836e3d2909e0040"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.71-sources.jar",
          "url": "core-ai-1.1.71-sources.jar",
          "size": 174081,
          "sha512": "106ba0324a5a7cfbccd180379d0a98ffeff8e04a66525a83122573d9548eadf8bf5a893f499a18cf3fa7aff4cbd5a67ae200d187a8490f96ff817a978948387f",
          "sha256": "743263380d42fc97ffc5ccbf7b1682d4dadffea4b053b996bf336313c4b5b2bc",
          "sha1": "f0455a483be3759aba1b995c67c684c98f387d08",
          "md5": "905180a18024a13814f115c1fd858e09"
        }
      ]
    }
  ]
}
