{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.46.jar",
          "url": "core-ai-1.1.46.jar",
          "size": 381624,
          "sha512": "aad90c0e5faeb9652ec5821e069fc1746c9f7c0584502fcfbcfd5f0a1cb80dd25063c1c6ee4180abefbeb0db1ef45bcfda2e36d3c0ce387ebf03f17662c65a06",
          "sha256": "44161bdd39f00506a96c3bb31c792d9e35fdf024727a3007c05b408bbebb7dba",
          "sha1": "c969c55f1391e5d4995f7703e89cfbf1aa15a2da",
          "md5": "3927cc097021fd120cd56d8ce3b76e17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.9"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.46.jar",
          "url": "core-ai-1.1.46.jar",
          "size": 381624,
          "sha512": "aad90c0e5faeb9652ec5821e069fc1746c9f7c0584502fcfbcfd5f0a1cb80dd25063c1c6ee4180abefbeb0db1ef45bcfda2e36d3c0ce387ebf03f17662c65a06",
          "sha256": "44161bdd39f00506a96c3bb31c792d9e35fdf024727a3007c05b408bbebb7dba",
          "sha1": "c969c55f1391e5d4995f7703e89cfbf1aa15a2da",
          "md5": "3927cc097021fd120cd56d8ce3b76e17"
        }
      ]
    }
  ]
}
