{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.62.jar",
          "url": "core-ai-1.1.62.jar",
          "size": 381718,
          "sha512": "97ccf29f4a2ce5927305604c4ddfb2773c08be3e5cecf4a7e1c7c60d03039a1a310d2ba8edd399bc888f53006a9a6b80bd0c822d560f6f419bb18096405ebc2b",
          "sha256": "f3e205ad215de1bfdfb99c48c95ee74a0cb18fa01f63e1815132d3d5ea5455e4",
          "sha1": "43971cf53d92899db5b7e3111fc7a7bdb4f20577",
          "md5": "adbdee0be7cad30d454a8d45029abf8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.9"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.62.jar",
          "url": "core-ai-1.1.62.jar",
          "size": 381718,
          "sha512": "97ccf29f4a2ce5927305604c4ddfb2773c08be3e5cecf4a7e1c7c60d03039a1a310d2ba8edd399bc888f53006a9a6b80bd0c822d560f6f419bb18096405ebc2b",
          "sha256": "f3e205ad215de1bfdfb99c48c95ee74a0cb18fa01f63e1815132d3d5ea5455e4",
          "sha1": "43971cf53d92899db5b7e3111fc7a7bdb4f20577",
          "md5": "adbdee0be7cad30d454a8d45029abf8e"
        }
      ]
    }
  ]
}
