{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.33.jar",
          "url": "core-ai-1.1.33.jar",
          "size": 380954,
          "sha512": "147fccf0d312b13682af7bec4992310170dcdf7803c909456e61fd77c988b0bef1647016707dab1965346bca09b1db5bc2c921812eeb871f9aa52da00411ba64",
          "sha256": "5bad0c277fc0d6060c544fbf0cee42b0d9cc732928abae6c22ddcec1da8e6b6a",
          "sha1": "94cbfe0a040d56f838f4cf6b4c71e32ac6eed5eb",
          "md5": "9c19f46febff48c17fcf02e53c501ac9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.33.jar",
          "url": "core-ai-1.1.33.jar",
          "size": 380954,
          "sha512": "147fccf0d312b13682af7bec4992310170dcdf7803c909456e61fd77c988b0bef1647016707dab1965346bca09b1db5bc2c921812eeb871f9aa52da00411ba64",
          "sha256": "5bad0c277fc0d6060c544fbf0cee42b0d9cc732928abae6c22ddcec1da8e6b6a",
          "sha1": "94cbfe0a040d56f838f4cf6b4c71e32ac6eed5eb",
          "md5": "9c19f46febff48c17fcf02e53c501ac9"
        }
      ]
    }
  ]
}
