{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.7.jar",
          "url": "core-ai-1.1.7.jar",
          "size": 353620,
          "sha512": "5d710dc3c216e1ed7b59c88ef1b4e914a6e93b4d675183845d8bc9db492a18ea3f7d51242ca75a4b219c00615421800a55037eddee64bbf4e11af6d782dd6755",
          "sha256": "3bbe23f3c31179250edea78c46840b1e7eacf08dbc4fbc048f1d156843fde6ff",
          "sha1": "5d83394d17988c9f28522c57b3c0a44d99848b28",
          "md5": "f3241ec727a8e77a81e842b7a73f97a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.7.jar",
          "url": "core-ai-1.1.7.jar",
          "size": 353620,
          "sha512": "5d710dc3c216e1ed7b59c88ef1b4e914a6e93b4d675183845d8bc9db492a18ea3f7d51242ca75a4b219c00615421800a55037eddee64bbf4e11af6d782dd6755",
          "sha256": "3bbe23f3c31179250edea78c46840b1e7eacf08dbc4fbc048f1d156843fde6ff",
          "sha1": "5d83394d17988c9f28522c57b3c0a44d99848b28",
          "md5": "f3241ec727a8e77a81e842b7a73f97a7"
        }
      ]
    }
  ]
}
