{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.1.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.13.jar",
          "url": "core-ai-api-1.1.13.jar",
          "size": 33190,
          "sha512": "854606db074f590bc71b7081583511696fb4e2323726f9009a6c0ee7cbcedd7e3a25b5d5ad50885c52bc6d53744d0138aad2905e9e46e824a3e4daba013e0b12",
          "sha256": "f1d52cbb353df2da20d36044503000611ad26b81f408a8585a0cbc68514eee44",
          "sha1": "813622d2f1dfa5827b7dd68194b622b937492c3e",
          "md5": "153af148b55b3c8b2a62a1f087312bef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.1.13.jar",
          "url": "core-ai-api-1.1.13.jar",
          "size": 33190,
          "sha512": "854606db074f590bc71b7081583511696fb4e2323726f9009a6c0ee7cbcedd7e3a25b5d5ad50885c52bc6d53744d0138aad2905e9e46e824a3e4daba013e0b12",
          "sha256": "f1d52cbb353df2da20d36044503000611ad26b81f408a8585a0cbc68514eee44",
          "sha1": "813622d2f1dfa5827b7dd68194b622b937492c3e",
          "md5": "153af148b55b3c8b2a62a1f087312bef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.13-sources.jar",
          "url": "core-ai-api-1.1.13-sources.jar",
          "size": 21492,
          "sha512": "8e251ebd0dd2c255e19b63fb8ba3a4fb509da5d1c546a4797e280ad7a1d796d6ea3a4c18a0a1d6be0428dc5e70e7abcefd7648bf5f9e74bc2a158231773afe54",
          "sha256": "9dd101a5933f8e08154ef87ad901a4cc91bbc4d36946cbeda9a97a6f7236f747",
          "sha1": "929cbc7638e6e6b960b55d428da22d7771f2856e",
          "md5": "70ebddc66b7329e0638f955829b127a0"
        }
      ]
    }
  ]
}
