{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.56.jar",
          "url": "core-ai-1.1.56.jar",
          "size": 380221,
          "sha512": "ef786d323296e30595d56eac64d323c975c2f857f3595c65f63562f1c93a75a9556d3fae49a7a6621c98cd5143490f5d1e69ab917b2cc7a0f3f686ff5d2ba9a0",
          "sha256": "db29bf0e1179cda4dffd992a4974756b0f93145f7b3ba4c03a38d704f96c1822",
          "sha1": "1a173c0e1bd30dc00c1bb9031d4e87c4f46a3cac",
          "md5": "8ee730ae2ae11ddea0b0d06f5078a9ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.56.jar",
          "url": "core-ai-1.1.56.jar",
          "size": 380221,
          "sha512": "ef786d323296e30595d56eac64d323c975c2f857f3595c65f63562f1c93a75a9556d3fae49a7a6621c98cd5143490f5d1e69ab917b2cc7a0f3f686ff5d2ba9a0",
          "sha256": "db29bf0e1179cda4dffd992a4974756b0f93145f7b3ba4c03a38d704f96c1822",
          "sha1": "1a173c0e1bd30dc00c1bb9031d4e87c4f46a3cac",
          "md5": "8ee730ae2ae11ddea0b0d06f5078a9ce"
        }
      ]
    }
  ]
}
