{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.85",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.85.jar",
          "url": "core-ai-1.1.85.jar",
          "size": 597178,
          "sha512": "e24de1511be681f7b581f86038a1492a0b6bd4216436010dd7199058b279f804bba431fe97208751dbd806b50af3d7c54fa92c522a44c999cd86f5ab1211a522",
          "sha256": "b11080b567992cd9861af08c4b57078aaecfdc13a047d7cb8c0f1864597936e2",
          "sha1": "4b58ab00ae0240dc3d71945df7a1735b88daf9d0",
          "md5": "e9bfd612e940ec82e85e08c9f75c1d79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.85.jar",
          "url": "core-ai-1.1.85.jar",
          "size": 597178,
          "sha512": "e24de1511be681f7b581f86038a1492a0b6bd4216436010dd7199058b279f804bba431fe97208751dbd806b50af3d7c54fa92c522a44c999cd86f5ab1211a522",
          "sha256": "b11080b567992cd9861af08c4b57078aaecfdc13a047d7cb8c0f1864597936e2",
          "sha1": "4b58ab00ae0240dc3d71945df7a1735b88daf9d0",
          "md5": "e9bfd612e940ec82e85e08c9f75c1d79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.85-sources.jar",
          "url": "core-ai-1.1.85-sources.jar",
          "size": 256207,
          "sha512": "288e2aac5109de54e090d7b6c6b6d3300fbff598fc6361c0e6a01b1c3f52eeecbec851b29a4c0eab505797db209bdf18d3a422540ac60bac01bd82fc7b7f9dce",
          "sha256": "6e0cfcd5926f32115775830b15d23c5f081a02f0fee62141652625c79cb3e463",
          "sha1": "6498fe20efe191b6ba49ba89cccecc91869fd2d0",
          "md5": "3ec92624c05b7003c7044bbb0596185a"
        }
      ]
    }
  ]
}
