{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.85",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.85.jar",
          "url": "core-ai-1.1.85.jar",
          "size": 508292,
          "sha512": "b6ddc928c82d51412ab5a80e946122db073ae0deca01c8462571adccb221e4303d2e02ba6111bc38fc6663a7a1f6e0673b8762e27b15f56e429d3c7b15d2407d",
          "sha256": "b9b126fc2a3c85b9b64f47247b005805b5b77a6bf7c3b52e8346991a1cb85ca8",
          "sha1": "13315119ee7cedfb0869b8a5366690c967627109",
          "md5": "4bc7cdd8ec32391600ed237f9a4cad72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.85.jar",
          "url": "core-ai-1.1.85.jar",
          "size": 508292,
          "sha512": "b6ddc928c82d51412ab5a80e946122db073ae0deca01c8462571adccb221e4303d2e02ba6111bc38fc6663a7a1f6e0673b8762e27b15f56e429d3c7b15d2407d",
          "sha256": "b9b126fc2a3c85b9b64f47247b005805b5b77a6bf7c3b52e8346991a1cb85ca8",
          "sha1": "13315119ee7cedfb0869b8a5366690c967627109",
          "md5": "4bc7cdd8ec32391600ed237f9a4cad72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.85-sources.jar",
          "url": "core-ai-1.1.85-sources.jar",
          "size": 220540,
          "sha512": "c94fcd87a5fe583c8019c09ba22e0f880707c673387e8083e1f1b2d0731773648ea5de875d20ceedc1fa7509a2df3e49d0005be77706f4bf53b7087f28b5a636",
          "sha256": "6046a81d6ffe79d3edd7dc8ec237f18aa7cf44e8e4595e092ceb561f14aa9621",
          "sha1": "f86e2f11e790bd8f43d8c0805f4eb46b58d69db2",
          "md5": "b8b0b7d5ea1e4ca8eab793b201a1b5bc"
        }
      ]
    }
  ]
}
