{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.85",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.85.jar",
          "url": "core-ai-1.1.85.jar",
          "size": 506019,
          "sha512": "0e515adc2a3e423ea5ee30e972235eca8735dd5384b06c134bba366c75a462ab850b1ecea9fca3403a69fb15642ffe05cfd09b3ff96045e7796e33af6aabe7ab",
          "sha256": "b27d7de3a3504f03daa737e4d6fa749174e2a1bf8de064eaa9c3d0a41076f62a",
          "sha1": "864dbfce8870d50f719a2f0ce000b3806b62dade",
          "md5": "7e3a8691b39837d352e25ccb0be98318"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.85.jar",
          "url": "core-ai-1.1.85.jar",
          "size": 506019,
          "sha512": "0e515adc2a3e423ea5ee30e972235eca8735dd5384b06c134bba366c75a462ab850b1ecea9fca3403a69fb15642ffe05cfd09b3ff96045e7796e33af6aabe7ab",
          "sha256": "b27d7de3a3504f03daa737e4d6fa749174e2a1bf8de064eaa9c3d0a41076f62a",
          "sha1": "864dbfce8870d50f719a2f0ce000b3806b62dade",
          "md5": "7e3a8691b39837d352e25ccb0be98318"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.85-sources.jar",
          "url": "core-ai-1.1.85-sources.jar",
          "size": 219515,
          "sha512": "7cfbed8974b651dfd46dff4ec2a3bdb6ed8a5f13456b3c4613b724f73f617019b0ac5cb022a14163fed8fa12b2a0d684618c45cf8461b2cdf69f1b3d32680077",
          "sha256": "ce86f2c4118dd530122c3941247f46a29925f950e12ca3d10972d3a63a502fc9",
          "sha1": "f40de05a593ef33421eab62175da823025f98e19",
          "md5": "17b858d62cfa9110b2f01fb3a57f7369"
        }
      ]
    }
  ]
}
