{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-vectorstore-milvus",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.6.8"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.66.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "core-ai-vectorstore-milvus-1.4.0-SNAPSHOT.jar",
          "url": "core-ai-vectorstore-milvus-1.4.0-SNAPSHOT.jar",
          "size": 21617,
          "sha512": "7d41b3516a4808fcc0199ff05616fad5afcdcd308abc853ed985ebb4fc0752c16e43f7d959961014d1852110ba6cc753fc2fd76cdc9153043138120a2866ebfb",
          "sha256": "49eab897d4ab7b18e3336f0c5b1cbe00ce515ae3b6e96dcb6deeada6462f1d35",
          "sha1": "aa06a16a64cc7fd6a9d4607891397aa56cfd178c",
          "md5": "6a004bd634d912a66ae28cc1cc21189a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai",
          "version": {
            "requires": "1.4.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.6.8"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.66.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "core-ai-vectorstore-milvus-1.4.0-SNAPSHOT.jar",
          "url": "core-ai-vectorstore-milvus-1.4.0-SNAPSHOT.jar",
          "size": 21617,
          "sha512": "7d41b3516a4808fcc0199ff05616fad5afcdcd308abc853ed985ebb4fc0752c16e43f7d959961014d1852110ba6cc753fc2fd76cdc9153043138120a2866ebfb",
          "sha256": "49eab897d4ab7b18e3336f0c5b1cbe00ce515ae3b6e96dcb6deeada6462f1d35",
          "sha1": "aa06a16a64cc7fd6a9d4607891397aa56cfd178c",
          "md5": "6a004bd634d912a66ae28cc1cc21189a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-vectorstore-milvus-1.4.0-SNAPSHOT-sources.jar",
          "url": "core-ai-vectorstore-milvus-1.4.0-SNAPSHOT-sources.jar",
          "size": 7862,
          "sha512": "5918ae7df75525ca57a4f4977763c355a00de2888a9fd5992e41f46334e7999e9c2b68847716b9248a9ed7171d43b4286af9bb7aee6108d3c38d50e55c931c0c",
          "sha256": "49c0815b62fde1972259101e109d2445acb62478a5c5945bb156580d3b9d1d9c",
          "sha1": "79f852c169d4f0a23033b97275f411512df80378",
          "md5": "6cb01482d2aeeac6c9a2a99450edebe2"
        }
      ]
    }
  ]
}
