{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.55.jar",
          "url": "core-ai-1.1.55.jar",
          "size": 380048,
          "sha512": "f953b22c8434b3f7506605fb0899692fd6912ada8c99e2449ba8e2b56e220656e7da6fb3aed22518c9ffbe3a71e65ec5e4229946a8e7bb368dad1a63f0908087",
          "sha256": "1deda4f8c54a1992cf6aa84833bb31a12ea506df3b35c3146717b873f0514ca5",
          "sha1": "62652edd0ee12153dad8a810aba08462daad60fd",
          "md5": "e9d40ad69d414c6c5c10879c5ecd2b31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.55.jar",
          "url": "core-ai-1.1.55.jar",
          "size": 380048,
          "sha512": "f953b22c8434b3f7506605fb0899692fd6912ada8c99e2449ba8e2b56e220656e7da6fb3aed22518c9ffbe3a71e65ec5e4229946a8e7bb368dad1a63f0908087",
          "sha256": "1deda4f8c54a1992cf6aa84833bb31a12ea506df3b35c3146717b873f0514ca5",
          "sha1": "62652edd0ee12153dad8a810aba08462daad60fd",
          "md5": "e9d40ad69d414c6c5c10879c5ecd2b31"
        }
      ]
    }
  ]
}
