{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.11.jar",
          "url": "core-ai-1.1.11.jar",
          "size": 376136,
          "sha512": "fc0515b5730ea76132067eb752c89a0bed84c33628a42bb4c7b60eea5524a723f8573e8fb3c1261d1ac428206de0fc00bf7e0ea7b54977806d11a983d24a4730",
          "sha256": "d43ed399d9358a8f328b0718dbad46a8fb659f29f5426539b3d24ed4279badc9",
          "sha1": "5e35b3388b3b4c91b0cd7e72c91017153cefbde0",
          "md5": "809eabd6dc685a7eac8e6b795210fdb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.11.jar",
          "url": "core-ai-1.1.11.jar",
          "size": 376136,
          "sha512": "fc0515b5730ea76132067eb752c89a0bed84c33628a42bb4c7b60eea5524a723f8573e8fb3c1261d1ac428206de0fc00bf7e0ea7b54977806d11a983d24a4730",
          "sha256": "d43ed399d9358a8f328b0718dbad46a8fb659f29f5426539b3d24ed4279badc9",
          "sha1": "5e35b3388b3b4c91b0cd7e72c91017153cefbde0",
          "md5": "809eabd6dc685a7eac8e6b795210fdb6"
        }
      ]
    }
  ]
}
