{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.0.0-SNAPSHOT.jar",
          "url": "litellm-library-1.0.0-SNAPSHOT.jar",
          "size": 27277,
          "sha512": "b2c894894a0e09fb2de3d5a54340d03da34226ec68c337d3baae36d71146edf3c63f52187cbd354d6aff12ccbebab7197a1393d8f1029fcf6037083737c5eed8",
          "sha256": "76363e11eeabaf599ceed11c248d7ff88c5ccef836601b0164504896e121ad33",
          "sha1": "9a9b4154f9b4a2c05888cbff1ce1f315fbae2586",
          "md5": "5bc9082f4eb8f5fd9196875a51f3a2af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.0.0-SNAPSHOT.jar",
          "url": "litellm-library-1.0.0-SNAPSHOT.jar",
          "size": 27277,
          "sha512": "b2c894894a0e09fb2de3d5a54340d03da34226ec68c337d3baae36d71146edf3c63f52187cbd354d6aff12ccbebab7197a1393d8f1029fcf6037083737c5eed8",
          "sha256": "76363e11eeabaf599ceed11c248d7ff88c5ccef836601b0164504896e121ad33",
          "sha1": "9a9b4154f9b4a2c05888cbff1ce1f315fbae2586",
          "md5": "5bc9082f4eb8f5fd9196875a51f3a2af"
        }
      ]
    }
  ]
}
