{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.0.0-SNAPSHOT.jar",
          "url": "litellm-library-1.0.0-SNAPSHOT.jar",
          "size": 27278,
          "sha512": "07598a01c9444b21ef9c1f7daa6bfb60ee599f9a54ba7cdb46bf5569b8b3fe3db0530e15f29eaf56c53d68fd807a71488cd22fefbd1c3f5bd2db8fe5dd6ce1b9",
          "sha256": "327cf62d5a4107f607c7eba3da1488768058aeacf0723c31103647cf011f7b6f",
          "sha1": "0c34e28ae38346d691141ebc02e7443e62e09ab2",
          "md5": "42e082e001e799377e29bb9ff6e7d152"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.0.0-SNAPSHOT.jar",
          "url": "litellm-library-1.0.0-SNAPSHOT.jar",
          "size": 27278,
          "sha512": "07598a01c9444b21ef9c1f7daa6bfb60ee599f9a54ba7cdb46bf5569b8b3fe3db0530e15f29eaf56c53d68fd807a71488cd22fefbd1c3f5bd2db8fe5dd6ce1b9",
          "sha256": "327cf62d5a4107f607c7eba3da1488768058aeacf0723c31103647cf011f7b6f",
          "sha1": "0c34e28ae38346d691141ebc02e7443e62e09ab2",
          "md5": "42e082e001e799377e29bb9ff6e7d152"
        }
      ]
    }
  ]
}
