{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.0.0-SNAPSHOT.jar",
          "url": "litellm-library-1.0.0-SNAPSHOT.jar",
          "size": 27235,
          "sha512": "e9ad5e15a940ea000026548e2f02fb64860822dc1114c7b2b68fb59a4f4ee41638e5dc088d89ceb865ce37c33882536a2fa2903d04407f1f6cea075d2040dc94",
          "sha256": "d146a1b2a46fe9894496aaf340723d650f8cc8efd1b8079b6d3c3bf3607b7c6f",
          "sha1": "8e74670a19338557b28dbccbb1765768b91bad08",
          "md5": "691a05ec77d4ae03143901106a8a1ac6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.0.0-SNAPSHOT.jar",
          "url": "litellm-library-1.0.0-SNAPSHOT.jar",
          "size": 27235,
          "sha512": "e9ad5e15a940ea000026548e2f02fb64860822dc1114c7b2b68fb59a4f4ee41638e5dc088d89ceb865ce37c33882536a2fa2903d04407f1f6cea075d2040dc94",
          "sha256": "d146a1b2a46fe9894496aaf340723d650f8cc8efd1b8079b6d3c3bf3607b7c6f",
          "sha1": "8e74670a19338557b28dbccbb1765768b91bad08",
          "md5": "691a05ec77d4ae03143901106a8a1ac6"
        }
      ]
    }
  ]
}
