{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.83",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.83.jar",
          "url": "core-ai-1.1.83.jar",
          "size": 417510,
          "sha512": "b3b5c653abfe3b7acc18346d54dcaa5ccb4e5b6b1b59663fd3b7ed27e34041baebdd94e9b2ed672f2238242bfd8e93051425c1ee5f4124f7ef9ceab38e4dc1ce",
          "sha256": "f642775370b3f5aaf62a7e5112d60a1c17b44e9f84a73ddbcf1361e6870a44e5",
          "sha1": "b0ec48b1f19572ca4bb9ebd251f27444be385078",
          "md5": "2d578139a76ac34138a3ae5e608b6e82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.83.jar",
          "url": "core-ai-1.1.83.jar",
          "size": 417510,
          "sha512": "b3b5c653abfe3b7acc18346d54dcaa5ccb4e5b6b1b59663fd3b7ed27e34041baebdd94e9b2ed672f2238242bfd8e93051425c1ee5f4124f7ef9ceab38e4dc1ce",
          "sha256": "f642775370b3f5aaf62a7e5112d60a1c17b44e9f84a73ddbcf1361e6870a44e5",
          "sha1": "b0ec48b1f19572ca4bb9ebd251f27444be385078",
          "md5": "2d578139a76ac34138a3ae5e608b6e82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.83-sources.jar",
          "url": "core-ai-1.1.83-sources.jar",
          "size": 175280,
          "sha512": "150287e8bac2bba946af845f9a81820df319d076c07425e24267c4723aaf16a3321cd7929a9c3d5edc3de33dfdaed134557e956d63856b1ccdd6d63f07a3b578",
          "sha256": "22e5c12878b9401528a942450a533763d3a11aab75f7a61055e674ce56a83b44",
          "sha1": "d4e4e0199b58d65d96b4f86b7bc7d4c14631bfa4",
          "md5": "4df33804ac8ade15507d537e1d67da0a"
        }
      ]
    }
  ]
}
