{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.32.jar",
          "url": "core-ai-1.1.32.jar",
          "size": 380954,
          "sha512": "b0edd7930b9d0e8f242e155e3667f43bd5fd0d4ad2a033f36bd58b85ba30ce375bf519e48e11057d07fdc6b25021aee5d07ade2fed0850b363494407b2c53e33",
          "sha256": "8e7c1d0e7d012d98eefdb7050dec8b85c4b8a19434ba436c6dff21379ab680ff",
          "sha1": "23abcaccb71a19147828634e171a5bcdc1acd0c9",
          "md5": "f254de17c748b772dd1acb967725e9f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.32.jar",
          "url": "core-ai-1.1.32.jar",
          "size": 380954,
          "sha512": "b0edd7930b9d0e8f242e155e3667f43bd5fd0d4ad2a033f36bd58b85ba30ce375bf519e48e11057d07fdc6b25021aee5d07ade2fed0850b363494407b2c53e33",
          "sha256": "8e7c1d0e7d012d98eefdb7050dec8b85c4b8a19434ba436c6dff21379ab680ff",
          "sha1": "23abcaccb71a19147828634e171a5bcdc1acd0c9",
          "md5": "f254de17c748b772dd1acb967725e9f5"
        }
      ]
    }
  ]
}
