{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.29.jar",
          "url": "core-ai-1.1.29.jar",
          "size": 380814,
          "sha512": "ccb0ea3fefd0dc52f497390a705a5ac150470cd3e7f5de89dd067ec43eed07a2a9b2c2280af2f29cf5f3f7b87b52aa0c3ac3257334e6123a65ce67e21e134c9d",
          "sha256": "6c9a961e25ef484b428c3417ab530de2618b1e269c2e907d8f26129409073905",
          "sha1": "824208b641525abec8146f3e601af560759e44ac",
          "md5": "c48badc38b7c44b581847943a7f21d4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.29.jar",
          "url": "core-ai-1.1.29.jar",
          "size": 380814,
          "sha512": "ccb0ea3fefd0dc52f497390a705a5ac150470cd3e7f5de89dd067ec43eed07a2a9b2c2280af2f29cf5f3f7b87b52aa0c3ac3257334e6123a65ce67e21e134c9d",
          "sha256": "6c9a961e25ef484b428c3417ab530de2618b1e269c2e907d8f26129409073905",
          "sha1": "824208b641525abec8146f3e601af560759e44ac",
          "md5": "c48badc38b7c44b581847943a7f21d4e"
        }
      ]
    }
  ]
}
