{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.100",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.100.jar",
          "url": "core-ai-1.1.100.jar",
          "size": 700814,
          "sha512": "027c7cd922f82def11e7c08faea01907d72028b3449afb22875e1efed9964028508b1049de24011ac77723cfeaf1c866530729baccfc86e7ae88b5c98c7bab88",
          "sha256": "24c53e4efb81e7c0a6b11f00a8a4bbced4d4c5d1ac8d22cf5c730096ba25b543",
          "sha1": "d7dea153cddb50a0aa1b6fd2a22d310dd98dd3c8",
          "md5": "2b948b454a79a05c27ccfff736ab04c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.100.jar",
          "url": "core-ai-1.1.100.jar",
          "size": 700814,
          "sha512": "027c7cd922f82def11e7c08faea01907d72028b3449afb22875e1efed9964028508b1049de24011ac77723cfeaf1c866530729baccfc86e7ae88b5c98c7bab88",
          "sha256": "24c53e4efb81e7c0a6b11f00a8a4bbced4d4c5d1ac8d22cf5c730096ba25b543",
          "sha1": "d7dea153cddb50a0aa1b6fd2a22d310dd98dd3c8",
          "md5": "2b948b454a79a05c27ccfff736ab04c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.100-sources.jar",
          "url": "core-ai-1.1.100-sources.jar",
          "size": 332792,
          "sha512": "0b67f6db67a14c09558b66a0521cf2580a50bfaa9a381e6bdb27536db675e7323ee01d845f8fbac58ca86b2d2a8311abe64b4fe6d21afbfe47ee4135625cb425",
          "sha256": "6c282d6c1dd4d1867c1592937b4756336a445ac017d710767ad68a73f0b07e28",
          "sha1": "3c4cacb91f7784c62520944a853e7dac5a4ebe6a",
          "md5": "c687e73351e6be4e72078cd7127691a5"
        }
      ]
    }
  ]
}
