{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.7.jar",
          "url": "core-ai-api-1.1.7.jar",
          "size": 33030,
          "sha512": "ed8ea07f4c3e0c6a8c1443bcf5101f5b715568dac715892f99fbec1923203c660a5e0230f9cd87256e292cdbf2d6f98056e60b71ee23d115245b3b1420da512f",
          "sha256": "501e89990798a5c60ae7e1a5e4ab71cf3d4cefc04ecfad66369adf7844902dc5",
          "sha1": "605e1fd115d9f97d45a01f8ef3529aa84fda79f4",
          "md5": "558b9956668576f626cf43a2008dcfcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.1.7.jar",
          "url": "core-ai-api-1.1.7.jar",
          "size": 33030,
          "sha512": "ed8ea07f4c3e0c6a8c1443bcf5101f5b715568dac715892f99fbec1923203c660a5e0230f9cd87256e292cdbf2d6f98056e60b71ee23d115245b3b1420da512f",
          "sha256": "501e89990798a5c60ae7e1a5e4ab71cf3d4cefc04ecfad66369adf7844902dc5",
          "sha1": "605e1fd115d9f97d45a01f8ef3529aa84fda79f4",
          "md5": "558b9956668576f626cf43a2008dcfcd"
        }
      ]
    }
  ]
}
