{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.105",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.105.jar",
          "url": "core-ai-1.1.105.jar",
          "size": 712516,
          "sha512": "68d9b3a95b92c18a718c6b70cd86b0a322fd915a200b8e968fb21ef1fe55df708fc4fbb40f0e7c111f911fdec846ad6eb09e282375c183c5cbb9b00c3b8dad58",
          "sha256": "1adaa808fb99f0a73e8d60321cb0699ca8988a35e2a1c2e2dba981264c6596a5",
          "sha1": "3a0a1c77a870abff528d8624c61451c658b224a1",
          "md5": "359f6477f6b98c4fc039cc387259b1b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.105.jar",
          "url": "core-ai-1.1.105.jar",
          "size": 712516,
          "sha512": "68d9b3a95b92c18a718c6b70cd86b0a322fd915a200b8e968fb21ef1fe55df708fc4fbb40f0e7c111f911fdec846ad6eb09e282375c183c5cbb9b00c3b8dad58",
          "sha256": "1adaa808fb99f0a73e8d60321cb0699ca8988a35e2a1c2e2dba981264c6596a5",
          "sha1": "3a0a1c77a870abff528d8624c61451c658b224a1",
          "md5": "359f6477f6b98c4fc039cc387259b1b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.105-sources.jar",
          "url": "core-ai-1.1.105-sources.jar",
          "size": 336386,
          "sha512": "02c9d8ca75d19dfdac7543b53c93ad2abaae1ce1d32d1e64113c95d5f4b8f3c62982275659d9839a1df020945e789be15c4bd54a6013cd3e7c7535a1a3e31946",
          "sha256": "923593b350fee6d8eb9a934e17ccb66a879cd14e339a9dc90eb6aeb943864e6f",
          "sha1": "7581046a5af87a48d741a419c81388371a9a03e0",
          "md5": "67eee3756666c83b83a155bd4255916f"
        }
      ]
    }
  ]
}
