{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.20.jar",
          "url": "core-ai-1.1.20.jar",
          "size": 377213,
          "sha512": "329fa5797bc6b7d7b9cc486afb8043cf54ae5b6922599526e473a07904c0761e4d95da63ea5c9d2025486fb6bb1423ce3f6dfe3c22028a0001f2532c186fc9fc",
          "sha256": "b240dbd2aeb1c8c25d0b5d96c78b2e358cee8c43a4a5ada011aa09108c5a35b3",
          "sha1": "a08f6d8e482392239c655a1dd9eeb63ea18fafcf",
          "md5": "a32a2820d7c691ea3892cc38bb65270f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.20.jar",
          "url": "core-ai-1.1.20.jar",
          "size": 377213,
          "sha512": "329fa5797bc6b7d7b9cc486afb8043cf54ae5b6922599526e473a07904c0761e4d95da63ea5c9d2025486fb6bb1423ce3f6dfe3c22028a0001f2532c186fc9fc",
          "sha256": "b240dbd2aeb1c8c25d0b5d96c78b2e358cee8c43a4a5ada011aa09108c5a35b3",
          "sha1": "a08f6d8e482392239c655a1dd9eeb63ea18fafcf",
          "md5": "a32a2820d7c691ea3892cc38bb65270f"
        }
      ]
    }
  ]
}
