{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.72",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.72.jar",
          "url": "core-ai-1.1.72.jar",
          "size": 417413,
          "sha512": "bc1cf022a75d72113e97d2194c108564f338b37c2bb70204e871b55fe4aea251cd550a4fa755a7d0826bb7949ba8b3f3e9c206d627bbf8cb20973d8e1171914f",
          "sha256": "fd8c208992c8b0a24c1f1bcf1a8b62920ff5c8484cbf0521c8f22faa72f345f7",
          "sha1": "733e68fa5bff5754731848a262a8e0e7922febfd",
          "md5": "2289abb09d6cfe193e934bbfb27e4ad5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.72.jar",
          "url": "core-ai-1.1.72.jar",
          "size": 417413,
          "sha512": "bc1cf022a75d72113e97d2194c108564f338b37c2bb70204e871b55fe4aea251cd550a4fa755a7d0826bb7949ba8b3f3e9c206d627bbf8cb20973d8e1171914f",
          "sha256": "fd8c208992c8b0a24c1f1bcf1a8b62920ff5c8484cbf0521c8f22faa72f345f7",
          "sha1": "733e68fa5bff5754731848a262a8e0e7922febfd",
          "md5": "2289abb09d6cfe193e934bbfb27e4ad5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.72-sources.jar",
          "url": "core-ai-1.1.72-sources.jar",
          "size": 174082,
          "sha512": "3a9847148a16b2e8ceb4bec873baa1f16e4fe1e0fb480d39c59899408313d61387825a218bfdccd2a0ef0f96ee2f5f4f97a97fc2b1c671ea1b63c10434bfbe64",
          "sha256": "4d32bc15302e8785610bdc5af464a57a2f94f3d40251716b937ce155f4b755b7",
          "sha1": "9eb42f2b8b980105b342025db5906663db7a654d",
          "md5": "249c2e54eece99e84dd9e531d98dd626"
        }
      ]
    }
  ]
}
