{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.4.jar",
          "url": "core-ai-1.1.4.jar",
          "size": 352971,
          "sha512": "9a3cba2fb4dce30c454a74f7842a42dc5effa2880c3dd42e20ac7c8d4879acde0bd85ad1957eb390724c0d6f46faa3cdc9005c5bb9f21664c630a8733f4f3af3",
          "sha256": "e1a070e9bb500b0d506cef21a64af3cfd7329ec94eff7ae813134677555a1a9d",
          "sha1": "76e00461e1d9a31b97c0175cc2871b3372dd2490",
          "md5": "d05cc1e424d2f2842d56756668d64332"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.4.jar",
          "url": "core-ai-1.1.4.jar",
          "size": 352971,
          "sha512": "9a3cba2fb4dce30c454a74f7842a42dc5effa2880c3dd42e20ac7c8d4879acde0bd85ad1957eb390724c0d6f46faa3cdc9005c5bb9f21664c630a8733f4f3af3",
          "sha256": "e1a070e9bb500b0d506cef21a64af3cfd7329ec94eff7ae813134677555a1a9d",
          "sha1": "76e00461e1d9a31b97c0175cc2871b3372dd2490",
          "md5": "d05cc1e424d2f2842d56756668d64332"
        }
      ]
    }
  ]
}
