{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.45.jar",
          "url": "core-ai-1.1.45.jar",
          "size": 381587,
          "sha512": "88e178166429169604b58c8392a119a4cc8bd81e1ee886138d465df04752c26ad1718785558108c415a517ae57095feb987749884492242f3088a78e3d6662fc",
          "sha256": "b6aa30657f8691ae3096b66dcbcda99f69113d5aa274969956f360cd7bebffce",
          "sha1": "c06fcd0b430dfba2b85d59d4912b055a29ecc689",
          "md5": "c40a01ee9ff31c961e91df0c25e70c7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.45.jar",
          "url": "core-ai-1.1.45.jar",
          "size": 381587,
          "sha512": "88e178166429169604b58c8392a119a4cc8bd81e1ee886138d465df04752c26ad1718785558108c415a517ae57095feb987749884492242f3088a78e3d6662fc",
          "sha256": "b6aa30657f8691ae3096b66dcbcda99f69113d5aa274969956f360cd7bebffce",
          "sha1": "c06fcd0b430dfba2b85d59d4912b055a29ecc689",
          "md5": "c40a01ee9ff31c961e91df0c25e70c7b"
        }
      ]
    }
  ]
}
