{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.104",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.104.jar",
          "url": "core-ai-1.1.104.jar",
          "size": 700988,
          "sha512": "20abafe997e1915fca92ca50e4e89385bef7dc7563d79fd93f981659ae070f7ef6fb0441940dd55ec01fca90e2b6840d51fdf4ffc233368c96423a668023ff60",
          "sha256": "30e1803f9b63716cb69c3068e7d5191377e597f12b9988ae94e06cf36af360ab",
          "sha1": "341fd513cb7628363f0fed53033d6100697e923e",
          "md5": "24fe1efd42e52176c28e5c79875500f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.104.jar",
          "url": "core-ai-1.1.104.jar",
          "size": 700988,
          "sha512": "20abafe997e1915fca92ca50e4e89385bef7dc7563d79fd93f981659ae070f7ef6fb0441940dd55ec01fca90e2b6840d51fdf4ffc233368c96423a668023ff60",
          "sha256": "30e1803f9b63716cb69c3068e7d5191377e597f12b9988ae94e06cf36af360ab",
          "sha1": "341fd513cb7628363f0fed53033d6100697e923e",
          "md5": "24fe1efd42e52176c28e5c79875500f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.104-sources.jar",
          "url": "core-ai-1.1.104-sources.jar",
          "size": 332859,
          "sha512": "953b387be66eca3016dd59e71000fa1af4172f2ebbb41cdac8ac3b6b806b37719d0c7ce7b1fce24c67899fe72a835fa9914e4bda38f4edab95958e6c95956d15",
          "sha256": "64531fcdfcd088a8cd9f397b174912624c8372e9e11ceadacbf2e60fb08545f4",
          "sha1": "6a4ce0fc37e72ab3d21e1989b00062cfe5b67d93",
          "md5": "0508d40f1ca8292f50e047310cfec14d"
        }
      ]
    }
  ]
}
