{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "agent-service-interface",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "agent-service-interface-1.0.3-SNAPSHOT.jar",
          "url": "agent-service-interface-1.0.3-SNAPSHOT.jar",
          "size": 9035,
          "sha512": "083d0675f5576c3f59f9642fdcea67e2bd2e01db51ced5a69a0805e5c60ce64edb6bb3f44f6a8b1c7fb8d83d38b7ca692de580985a65d41581c74353f9591fc0",
          "sha256": "65b8a4001195d0c7258b33176d5c931042062eff4bd8835657a9423ba0df7a6d",
          "sha1": "e55472a4c657f96e96521cf82ce060ec48c3d643",
          "md5": "2ce1dc9925b32dd0b68261a5058a97d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "agent-service-interface-1.0.3-SNAPSHOT.jar",
          "url": "agent-service-interface-1.0.3-SNAPSHOT.jar",
          "size": 9035,
          "sha512": "083d0675f5576c3f59f9642fdcea67e2bd2e01db51ced5a69a0805e5c60ce64edb6bb3f44f6a8b1c7fb8d83d38b7ca692de580985a65d41581c74353f9591fc0",
          "sha256": "65b8a4001195d0c7258b33176d5c931042062eff4bd8835657a9423ba0df7a6d",
          "sha1": "e55472a4c657f96e96521cf82ce060ec48c3d643",
          "md5": "2ce1dc9925b32dd0b68261a5058a97d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "agent-service-interface-1.0.3-SNAPSHOT-sources.jar",
          "url": "agent-service-interface-1.0.3-SNAPSHOT-sources.jar",
          "size": 6472,
          "sha512": "8c881dee8a04e4671118b1039eb227842aab30a8eefdd0581e650b2e40a1d0b2534c410200493fe4b5addc68041bd08e7d2c6ca3c0b6bb0ae7ca829b7df5f805",
          "sha256": "4b28106807086f71ff08c9698dd55f6242ca77120f9b8eaf95870ba8cbcc64e5",
          "sha1": "f466c536134ceb0e7ae6207317db342cb39fcda7",
          "md5": "c36d3ed353e396b69a0a7dccaa047b8d"
        }
      ]
    }
  ]
}
