{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.1.10.jar",
          "url": "litellm-library-1.1.10.jar",
          "size": 27328,
          "sha512": "48cc4def1481300cc7f105dcd6ed4995acb221c0222678ed83c5563954f3675b8f533f3166739e736a669a22abec6773ee5cb34eb8d56c764a5000125f306d92",
          "sha256": "86296fdeadaea88bef8cc6bfa0d2289d4c6484f08f91c96b7ace4dbfcab65237",
          "sha1": "fd26d207e5415a45d6d2947cb24c76562c81e7e1",
          "md5": "b9991069f32a1fd6f614dc3fc76cc4fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.1.10.jar",
          "url": "litellm-library-1.1.10.jar",
          "size": 27328,
          "sha512": "48cc4def1481300cc7f105dcd6ed4995acb221c0222678ed83c5563954f3675b8f533f3166739e736a669a22abec6773ee5cb34eb8d56c764a5000125f306d92",
          "sha256": "86296fdeadaea88bef8cc6bfa0d2289d4c6484f08f91c96b7ace4dbfcab65237",
          "sha1": "fd26d207e5415a45d6d2947cb24c76562c81e7e1",
          "md5": "b9991069f32a1fd6f614dc3fc76cc4fb"
        }
      ]
    }
  ]
}
