{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.11.jar",
          "url": "core-ai-api-1.1.11.jar",
          "size": 32566,
          "sha512": "f785c7796e67deafb01d1e1685ba919f68412dcd4f89c3ba635d9f4c1ca870266533cf6044b9e80f1acd035c4367601af7707efc9da4e41d06de26733d23d4b4",
          "sha256": "b925f2458614fa5104c357dfb3b054608a43c3fcf48c1e62cf349a033297ebc2",
          "sha1": "ad680a7e2df18be41e9701f654bab72a75c6e4f6",
          "md5": "e44e1b0cf78b0f1dfa580346d20265dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.1.11.jar",
          "url": "core-ai-api-1.1.11.jar",
          "size": 32566,
          "sha512": "f785c7796e67deafb01d1e1685ba919f68412dcd4f89c3ba635d9f4c1ca870266533cf6044b9e80f1acd035c4367601af7707efc9da4e41d06de26733d23d4b4",
          "sha256": "b925f2458614fa5104c357dfb3b054608a43c3fcf48c1e62cf349a033297ebc2",
          "sha1": "ad680a7e2df18be41e9701f654bab72a75c6e4f6",
          "md5": "e44e1b0cf78b0f1dfa580346d20265dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.11-sources.jar",
          "url": "core-ai-api-1.1.11-sources.jar",
          "size": 21090,
          "sha512": "69155e6be29434c51f83da60a6372d3662aebcd613c927b84dccac6330054037dfe15145f40d8b0875b877b70eb0999a1343eb2b1479c9d9802dc779f2a6ac69",
          "sha256": "59c6c9c8dd6b7b9d9376e08dabe7bc1972e8f48e354189764eff6e7d701daeb4",
          "sha1": "7ab01753d57796ded84933fee864ea0f33200060",
          "md5": "3c757fa171f9102e20f489a09477a978"
        }
      ]
    }
  ]
}
