{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.77",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.77.jar",
          "url": "core-ai-1.1.77.jar",
          "size": 416410,
          "sha512": "64a8e878da99e74e67848078a01c53a3fdf1bf8de83d5b7a9652d788e0cf29608ddbe47395b396c5dbe8ab39530588d66a4224c5e30c4800a17e86f3588299d2",
          "sha256": "928634eed890a21d4c9e4c355d7834dcca83ba057086132bb7d5bba751c7198a",
          "sha1": "b238efbb1d9aefe4138e4a148e4df5b9cac9d8d9",
          "md5": "3afa360cd5fd4e2ec743d06ad052253b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.77.jar",
          "url": "core-ai-1.1.77.jar",
          "size": 416410,
          "sha512": "64a8e878da99e74e67848078a01c53a3fdf1bf8de83d5b7a9652d788e0cf29608ddbe47395b396c5dbe8ab39530588d66a4224c5e30c4800a17e86f3588299d2",
          "sha256": "928634eed890a21d4c9e4c355d7834dcca83ba057086132bb7d5bba751c7198a",
          "sha1": "b238efbb1d9aefe4138e4a148e4df5b9cac9d8d9",
          "md5": "3afa360cd5fd4e2ec743d06ad052253b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.77-sources.jar",
          "url": "core-ai-1.1.77-sources.jar",
          "size": 174802,
          "sha512": "ba3c141afcf294cf7167356ecb9a6de779fe85f53c92c61a94b1de9cc4d2d1ad10795852da85e6146217798236436ecbb1e451049b8032459defeadacd99f78c",
          "sha256": "b1782835f0d4c5621d10f0f01b2f4c707371b34867e2d814fc9503eb9153021e",
          "sha1": "977275f237fcfa8a8a1d671575d4b39311e28e3e",
          "md5": "979633187310097375419eab2395c88f"
        }
      ]
    }
  ]
}
