{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.0.jar",
          "url": "core-ai-1.1.0.jar",
          "size": 353158,
          "sha512": "c8920c67257a0d95d364daa1a2a78157a74b55508d19982646c71b4b5a3ef4fcef5eb91e03dc89c9da259bf5d0e3311c07a6b25924ec18f3411b425d2ae45d00",
          "sha256": "aac4083aa990e78f5540b4efa20cbd1e9ddb0ec0ae66c95d21f02c458f21538b",
          "sha1": "b98f8bfbb64d1255b8439e29708e71301b11d711",
          "md5": "455ab20f8cb8ebf458cc1c7b9553973a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.0.jar",
          "url": "core-ai-1.1.0.jar",
          "size": 353158,
          "sha512": "c8920c67257a0d95d364daa1a2a78157a74b55508d19982646c71b4b5a3ef4fcef5eb91e03dc89c9da259bf5d0e3311c07a6b25924ec18f3411b425d2ae45d00",
          "sha256": "aac4083aa990e78f5540b4efa20cbd1e9ddb0ec0ae66c95d21f02c458f21538b",
          "sha1": "b98f8bfbb64d1255b8439e29708e71301b11d711",
          "md5": "455ab20f8cb8ebf458cc1c7b9553973a"
        }
      ]
    }
  ]
}
