{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 92910,
          "sha512": "739f6009534caaa14a9373e175bfe24afc1b378231efe2ccd39e0f69cf6c2675f587d02ef4d53476b037cdcc2091d2311f1e6fa5f4b60e1ec9d2566f50bf4534",
          "sha256": "ba2bac8dd3af9a0867dd4477f22ff634eec5f29623c504f56918394a47ee8210",
          "sha1": "268040e3e94b832aa354100120250b459d5b0220",
          "md5": "f93ced69133398ea5a9b7eaf85959b41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 92910,
          "sha512": "739f6009534caaa14a9373e175bfe24afc1b378231efe2ccd39e0f69cf6c2675f587d02ef4d53476b037cdcc2091d2311f1e6fa5f4b60e1ec9d2566f50bf4534",
          "sha256": "ba2bac8dd3af9a0867dd4477f22ff634eec5f29623c504f56918394a47ee8210",
          "sha1": "268040e3e94b832aa354100120250b459d5b0220",
          "md5": "f93ced69133398ea5a9b7eaf85959b41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "size": 55792,
          "sha512": "8fc9f875c3d2997c4dd59c7ee38fe0c29943c0035226467aa5cee734d9c011c8ef87a5ce2faf410e6b76d284ce692c4c36cc9035f14d7a43f58e1283f94bd65b",
          "sha256": "6f2697f7858268b536ff9e68fac449ff2717e5e042e3ce9b3335a372d88b14f6",
          "sha1": "0b3733129edf3291352ac876e62dea6a7eece770",
          "md5": "cec7eab72d61b77dbf71f9d3eac5b369"
        }
      ]
    }
  ]
}
