{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 198614,
          "sha512": "01a5b8cb1df6a3e019b05ec89e6fd5ac8f83c83837092255eb4eaf3159f5a0bcb24fb0c61f62268966530d1775587dffcd9880444bb499f5443580a9e348c60d",
          "sha256": "02c5d7dbddd82bade5f7a742e00ea9f1475175b02d6dd5eac0379a7cf5f4508e",
          "sha1": "51ce7bc71c651d180441521676ab87d8b56a18cd",
          "md5": "43394f9ccbc53da45c1d0b5cc14adda7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 198614,
          "sha512": "01a5b8cb1df6a3e019b05ec89e6fd5ac8f83c83837092255eb4eaf3159f5a0bcb24fb0c61f62268966530d1775587dffcd9880444bb499f5443580a9e348c60d",
          "sha256": "02c5d7dbddd82bade5f7a742e00ea9f1475175b02d6dd5eac0379a7cf5f4508e",
          "sha1": "51ce7bc71c651d180441521676ab87d8b56a18cd",
          "md5": "43394f9ccbc53da45c1d0b5cc14adda7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "size": 127757,
          "sha512": "2887aa781c7c85fc4ed75726b6e866431dc12fa57f64dc893576a84a084bd7edb5071eadf705265cc0e4e5cb568ecdd63465b3a9252a0a80a0efb2786ca52322",
          "sha256": "23e896cce9ca179d431c0ad6c35ee1068374cfd460f3505e1ed2becf8747b7dc",
          "sha1": "acecbb18efcec5dbd1b30f10b85162fa997d2047",
          "md5": "f242b83de0c1c368f766d7b9fe5d130c"
        }
      ]
    }
  ]
}
