{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 198968,
          "sha512": "b0a7ca4eb81e4a543b5f2669de52f25cb2a47f6d9141916cda97721b650519e0ecef7f92ee59c055ea4ec9e65b3fae8363c10189165d78aafe1323e3cb26e889",
          "sha256": "82b898b004c62dc7afac5ad0db03dc9bb13b05fa38477023340844a8e2d0eec2",
          "sha1": "708080d99e8bd287a0aa0a5230115fa4c94c8cb9",
          "md5": "cc231e84d17c20f1a4f5f1b2f46cb15b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 198968,
          "sha512": "b0a7ca4eb81e4a543b5f2669de52f25cb2a47f6d9141916cda97721b650519e0ecef7f92ee59c055ea4ec9e65b3fae8363c10189165d78aafe1323e3cb26e889",
          "sha256": "82b898b004c62dc7afac5ad0db03dc9bb13b05fa38477023340844a8e2d0eec2",
          "sha1": "708080d99e8bd287a0aa0a5230115fa4c94c8cb9",
          "md5": "cc231e84d17c20f1a4f5f1b2f46cb15b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "size": 128124,
          "sha512": "bfe9737b8d395a7250c8d1c2acafefdecc29274926eb6c8694d18c6c22f755be8ae4dd144dd9ce48ff2f0e048ca1b155956f3845b75c92f176b155efc0c40796",
          "sha256": "677788c41f7906fe634809f787fae9e24e866fda0d853fda5bbd3685c9222659",
          "sha1": "b51335d2eec9cf5f8dae8c88da0835e1d9114000",
          "md5": "8a7cd48194f99da03f4f807415879013"
        }
      ]
    }
  ]
}
