{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 74449,
          "sha512": "84bfdd59627869676e2d0e4f28867bef3b10db6b30c31b8a1bcae1db275d88282599e8e6aae1cb17f59728a6b472b361137872ae1b8fb7053ed5aa9455bca838",
          "sha256": "27c086f2779a3de80c35194d397e5f16f3bdfd984a45c800a29d9f731d14023f",
          "sha1": "959031604cc39e5529389b00d8674ccdcbff9a2f",
          "md5": "478f9a6129068c5e426af51528903008"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 74449,
          "sha512": "84bfdd59627869676e2d0e4f28867bef3b10db6b30c31b8a1bcae1db275d88282599e8e6aae1cb17f59728a6b472b361137872ae1b8fb7053ed5aa9455bca838",
          "sha256": "27c086f2779a3de80c35194d397e5f16f3bdfd984a45c800a29d9f731d14023f",
          "sha1": "959031604cc39e5529389b00d8674ccdcbff9a2f",
          "md5": "478f9a6129068c5e426af51528903008"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "size": 47490,
          "sha512": "4d5eb6e97269280eab8441f286d4a9a92c3ca6cd6625aefc54fc3e5ce58748a8dc821a00643c64a682e406fe090d94c22f7780388ea0636552f00e4ef65aa3c1",
          "sha256": "8a8fbdc6b3a9269d549c74c0414aa61592dd84ff0386d36a80927bb58f19febc",
          "sha1": "b42b091f8fcf4cadd590e4ee27e8606cb9bdaaec",
          "md5": "170d16f7ece19fd6413b2adbe5b7df0c"
        }
      ]
    }
  ]
}
