{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 326304,
          "sha512": "e41ff2e000312dcab08ad5b967e790a8d85f7fd67e1aef86b98ab3b26a2ba51c37001ba55e1ccbc52a0bb58bd0e590fe90f33d19d2d8660dfa84ed636f16f277",
          "sha256": "d02bc490345a523dac1b006793b1541d588ab0d0329fdf5b7ce30d8e4dd30c1f",
          "sha1": "0cd502009c83920e0080820a9ecdb9604ce29e92",
          "md5": "1e8c1039cb7be8af33831a1fc9fc24bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 326304,
          "sha512": "e41ff2e000312dcab08ad5b967e790a8d85f7fd67e1aef86b98ab3b26a2ba51c37001ba55e1ccbc52a0bb58bd0e590fe90f33d19d2d8660dfa84ed636f16f277",
          "sha256": "d02bc490345a523dac1b006793b1541d588ab0d0329fdf5b7ce30d8e4dd30c1f",
          "sha1": "0cd502009c83920e0080820a9ecdb9604ce29e92",
          "md5": "1e8c1039cb7be8af33831a1fc9fc24bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "size": 219950,
          "sha512": "9510e43be28ea3c81f1fdb7044c140dc5065e09441b1e07c23049a607a62248863b5df6e5105f4f65b1e9f9fe95ff3a44e3f15f7fe5f9aabfccad9b4e424e151",
          "sha256": "750036eb079d1dd143803fd538fefde177b4a6ced383127a1c73fe97ed04a446",
          "sha1": "4f5ef2353477d1be171c70f8ce8b59effa657f5d",
          "md5": "90a2460b54364f1ad62fc53e5d013bfc"
        }
      ]
    }
  ]
}
