{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 53254,
          "sha512": "54479ebd98e927eda388165189bce852f8e6b324ac464c8cc592a1d63fe80a268214dcbe2b6ba18c984544ad4d50d5920e29c12d11492b4314beceaab8c90e9c",
          "sha256": "de80b50b81fcac2b1984a0f8a3a8035700157bd0811df84d810ab69c42787bf2",
          "sha1": "cb64ab4669984a31e755f703d833f58a0681fea7",
          "md5": "177b053ed917ecc55f2cc944b68437d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 53254,
          "sha512": "54479ebd98e927eda388165189bce852f8e6b324ac464c8cc592a1d63fe80a268214dcbe2b6ba18c984544ad4d50d5920e29c12d11492b4314beceaab8c90e9c",
          "sha256": "de80b50b81fcac2b1984a0f8a3a8035700157bd0811df84d810ab69c42787bf2",
          "sha1": "cb64ab4669984a31e755f703d833f58a0681fea7",
          "md5": "177b053ed917ecc55f2cc944b68437d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "size": 31940,
          "sha512": "8587c176d2044fc79d11ddd80a1f9fe667580dadab9cf7c0f37af389873bacc995d67bda4a8f29c26c2652bed0caeade99d8628f8979b5c59c60b647b3b6ec96",
          "sha256": "f25ed5e8764bb3b3e62706c76a201833a58f5edc5f6481ef662a00ed4f2bc23a",
          "sha1": "c82d2df783ef9bdc458c6ebb711e26aa5c63e0eb",
          "md5": "c8172f541561ceb397b2fd80d261ff89"
        }
      ]
    }
  ]
}
