{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 53257,
          "sha512": "d70fee52c61c937e964559cba9ac192daba64e3f9b7065300c9347629dd1eef38859cf3cc530bc784e7b35020b26f59f100869219365b5a85d6723a5a8e782f1",
          "sha256": "390b96d2104e9b5b204b241edc2069dda9aaad91af87f9d9ad374a958e605d39",
          "sha1": "4d0b9e7f4f0dd120fb80dde9f388349c9e3af234",
          "md5": "43aa1a49fcd191379822c27f3a884092"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT.jar",
          "size": 53257,
          "sha512": "d70fee52c61c937e964559cba9ac192daba64e3f9b7065300c9347629dd1eef38859cf3cc530bc784e7b35020b26f59f100869219365b5a85d6723a5a8e782f1",
          "sha256": "390b96d2104e9b5b204b241edc2069dda9aaad91af87f9d9ad374a958e605d39",
          "sha1": "4d0b9e7f4f0dd120fb80dde9f388349c9e3af234",
          "md5": "43aa1a49fcd191379822c27f3a884092"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.3.0-SNAPSHOT-sources.jar",
          "size": 31400,
          "sha512": "0c5eca1e09f1087266c43de06e94af91e328c26bd239f2732e1936780426d982683ce9004ecdbf346a853b963870b627ff416d1450020d64aaece17b83275a33",
          "sha256": "0bf34dbe13c50a37a96873ed994a630b565bfe9632c25ea5c9cbace9d4ed8ced",
          "sha1": "bddd2cbecfdac6285a5f012bd360dd1b29db7e6d",
          "md5": "caddba471468b87c7be65740a3cec33e"
        }
      ]
    }
  ]
}
