{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.28.jar",
          "url": "core-ai-1.1.28.jar",
          "size": 380825,
          "sha512": "c16166f0bb12ab19763ed609f4f59a97b61302e7492da48753e43108f4e78961418166676f529d147f7379d3c7ccc1dc291e72a8b311066e1e91ca2814fb325e",
          "sha256": "29ac0275c4b510e719dd4abc2a293ed8fbb7639b59474f720d1834a2e3e84fd5",
          "sha1": "422139be76db75ed2712f189ee8d31fb486b540b",
          "md5": "bb6e4ca51ba2f7265ef4456c2927b9e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.28.jar",
          "url": "core-ai-1.1.28.jar",
          "size": 380825,
          "sha512": "c16166f0bb12ab19763ed609f4f59a97b61302e7492da48753e43108f4e78961418166676f529d147f7379d3c7ccc1dc291e72a8b311066e1e91ca2814fb325e",
          "sha256": "29ac0275c4b510e719dd4abc2a293ed8fbb7639b59474f720d1834a2e3e84fd5",
          "sha1": "422139be76db75ed2712f189ee8d31fb486b540b",
          "md5": "bb6e4ca51ba2f7265ef4456c2927b9e1"
        }
      ]
    }
  ]
}
