{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.68.jar",
          "url": "core-ai-1.1.68.jar",
          "size": 417482,
          "sha512": "838b94f0d1b81af0aef21781da43f3835c879d43eb4462c9c5dc862632e4dcfe685d86412b8cf9a61165fd9ca362602d551e51af0ffca8df24ea7e5e3ec38b48",
          "sha256": "b622347bffdf6cc38e74ead43486d6b025836fe20e4648a065b71403492046d3",
          "sha1": "b0b5042af9712eb1cc1c939f8f8e39e4eddbdf65",
          "md5": "25ed473cb8ef33e7961060b1aef76a50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.12"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.68.jar",
          "url": "core-ai-1.1.68.jar",
          "size": 417482,
          "sha512": "838b94f0d1b81af0aef21781da43f3835c879d43eb4462c9c5dc862632e4dcfe685d86412b8cf9a61165fd9ca362602d551e51af0ffca8df24ea7e5e3ec38b48",
          "sha256": "b622347bffdf6cc38e74ead43486d6b025836fe20e4648a065b71403492046d3",
          "sha1": "b0b5042af9712eb1cc1c939f8f8e39e4eddbdf65",
          "md5": "25ed473cb8ef33e7961060b1aef76a50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.68-sources.jar",
          "url": "core-ai-1.1.68-sources.jar",
          "size": 173988,
          "sha512": "a67f0f89113fc59c8b4c46ca6872a69dfdea5adbbe9f8ad0a5549396e8fd69c1c8485b9c2325cad6ab43ca3b3aee05b5b0786bf5d050dd908051e6f4e4cbcf0b",
          "sha256": "25df72df717b4dae024f57d094a10b7948357311966fac9b1928217a56bca298",
          "sha1": "51bbd179b377f2ec01c05c53cd4da4e04476ff00",
          "md5": "6a1a2db24e525cc3ecca2e57a99352e4"
        }
      ]
    }
  ]
}
