{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.39.jar",
          "url": "core-ai-1.1.39.jar",
          "size": 381201,
          "sha512": "f947b557274d0d32e93f7d5bc0eccf9c13bd507b1af08ea260e972d7a86a0bd48dacdc303f1a0992b0e0bdb6d7669461a9d9c25e55e0d692e425d56ee30df670",
          "sha256": "f9ce9e29bca2ce04ac9753a03e7447bf04c1fdd536e8944ac8521f4b7a7a72e9",
          "sha1": "4a3b56d416b1e2e5d7172be31c852cce1c8a6f42",
          "md5": "833ecff082ce6024435b6811ebfd8337"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.39.jar",
          "url": "core-ai-1.1.39.jar",
          "size": 381201,
          "sha512": "f947b557274d0d32e93f7d5bc0eccf9c13bd507b1af08ea260e972d7a86a0bd48dacdc303f1a0992b0e0bdb6d7669461a9d9c25e55e0d692e425d56ee30df670",
          "sha256": "f9ce9e29bca2ce04ac9753a03e7447bf04c1fdd536e8944ac8521f4b7a7a72e9",
          "sha1": "4a3b56d416b1e2e5d7172be31c852cce1c8a6f42",
          "md5": "833ecff082ce6024435b6811ebfd8337"
        }
      ]
    }
  ]
}
