{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.3.jar",
          "url": "core-ai-1.1.3.jar",
          "size": 352903,
          "sha512": "e096863d8bb55e46e0432718705b9744f7886a2268f1c9cf669ab131b2d703d78e1fa0615ef45ec9d616ecdd1f02c5f10ec264baf678bed53b9b288598986d44",
          "sha256": "bdf2ca45a86e9405d0b04b4184ae391ee954d7ccc3773f4cb04139c7e1a86c40",
          "sha1": "de0432b141db013a69d2ec78b643ad0ef9635ae6",
          "md5": "cef514ba904a5614ed04db7f30066289"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.3.jar",
          "url": "core-ai-1.1.3.jar",
          "size": 352903,
          "sha512": "e096863d8bb55e46e0432718705b9744f7886a2268f1c9cf669ab131b2d703d78e1fa0615ef45ec9d616ecdd1f02c5f10ec264baf678bed53b9b288598986d44",
          "sha256": "bdf2ca45a86e9405d0b04b4184ae391ee954d7ccc3773f4cb04139c7e1a86c40",
          "sha1": "de0432b141db013a69d2ec78b643ad0ef9635ae6",
          "md5": "cef514ba904a5614ed04db7f30066289"
        }
      ]
    }
  ]
}
