{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0.jar",
          "url": "core-ai-1.0.0.jar",
          "size": 173398,
          "sha512": "4f5915fe359da1308a49d334cce99769e0747d19a96cc728d0d2462767836dcaaf83d81a0cacee4e6432c1a8a9c044661210471cb677c9d5af33e4f37be71b48",
          "sha256": "0ad2a261a55b5cba69bb5dc1eb9cfebb0648bf77f7eb2438ab10c6ec96c8b34c",
          "sha1": "240406d088962a56d68f8992b8e26ced999eab34",
          "md5": "6a63b767d9f98c070a0517b332421ed5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.theokanning.openai-gpt3-java",
          "module": "client",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.11"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "io.modelcontextprotocol",
          "module": "kotlin-sdk",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.0.0.jar",
          "url": "core-ai-1.0.0.jar",
          "size": 173398,
          "sha512": "4f5915fe359da1308a49d334cce99769e0747d19a96cc728d0d2462767836dcaaf83d81a0cacee4e6432c1a8a9c044661210471cb677c9d5af33e4f37be71b48",
          "sha256": "0ad2a261a55b5cba69bb5dc1eb9cfebb0648bf77f7eb2438ab10c6ec96c8b34c",
          "sha1": "240406d088962a56d68f8992b8e26ced999eab34",
          "md5": "6a63b767d9f98c070a0517b332421ed5"
        }
      ]
    }
  ]
}
