{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.1.jar",
          "url": "core-ai-1.1.1.jar",
          "size": 353170,
          "sha512": "3ac454978b05e2a33d3bddd6b6c2d6833c45eb0b502a28f1502cd02158bb9ecc8c1602619c4767de6762124ec50c036124352e89ee56a9f41b84e4ecc7d83e41",
          "sha256": "0615d06314453a5285ce814b2fbfc131764bbad54ee35d532d97c25b4dd7265d",
          "sha1": "f8536951855f3de085881b533f823085bab9322b",
          "md5": "1903e669b0193f0728e6284efd559158"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.1.jar",
          "url": "core-ai-1.1.1.jar",
          "size": 353170,
          "sha512": "3ac454978b05e2a33d3bddd6b6c2d6833c45eb0b502a28f1502cd02158bb9ecc8c1602619c4767de6762124ec50c036124352e89ee56a9f41b84e4ecc7d83e41",
          "sha256": "0615d06314453a5285ce814b2fbfc131764bbad54ee35d532d97c25b4dd7265d",
          "sha1": "f8536951855f3de085881b533f823085bab9322b",
          "md5": "1903e669b0193f0728e6284efd559158"
        }
      ]
    }
  ]
}
