{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.30.jar",
          "url": "core-ai-1.1.30.jar",
          "size": 380768,
          "sha512": "bf5792b669f7efaa209be9c7645537b44c994c209ea4c7fa22ee84c7ae3a0fb7f71af3d96961237022f51e0a1ab436760fe4c98cf4832ec52f358443abe22c08",
          "sha256": "04ed5c0943be35a07cf97a9c5a57e10b3090415c458412265e86bf02cefecf83",
          "sha1": "7edfa0d5a4e1ae5b06765716d809015f358199ac",
          "md5": "626206ab742af5d71a7ad4441c0fb4f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.30.jar",
          "url": "core-ai-1.1.30.jar",
          "size": 380768,
          "sha512": "bf5792b669f7efaa209be9c7645537b44c994c209ea4c7fa22ee84c7ae3a0fb7f71af3d96961237022f51e0a1ab436760fe4c98cf4832ec52f358443abe22c08",
          "sha256": "04ed5c0943be35a07cf97a9c5a57e10b3090415c458412265e86bf02cefecf83",
          "sha1": "7edfa0d5a4e1ae5b06765716d809015f358199ac",
          "md5": "626206ab742af5d71a7ad4441c0fb4f1"
        }
      ]
    }
  ]
}
