{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.9.jar",
          "url": "core-ai-1.1.9.jar",
          "size": 375963,
          "sha512": "fdc3f4dd629203724620aa55918bef5b710bdd24588b1afe6930ecfade99bfc79b68decbf930c46b13de3e738fe3e5c6924e6394ee8d5631c855f97031f7397a",
          "sha256": "24264038494d54670affe51453ff39e36c53da9c46f6b3164bf6a13590b6f82f",
          "sha1": "cd3e3ee09463b2c588d28dfc4975ff110efcc904",
          "md5": "a108a34508c6291450f3b39e60a7cc1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.9.jar",
          "url": "core-ai-1.1.9.jar",
          "size": 375963,
          "sha512": "fdc3f4dd629203724620aa55918bef5b710bdd24588b1afe6930ecfade99bfc79b68decbf930c46b13de3e738fe3e5c6924e6394ee8d5631c855f97031f7397a",
          "sha256": "24264038494d54670affe51453ff39e36c53da9c46f6b3164bf6a13590b6f82f",
          "sha1": "cd3e3ee09463b2c588d28dfc4975ff110efcc904",
          "md5": "a108a34508c6291450f3b39e60a7cc1f"
        }
      ]
    }
  ]
}
