{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.26.jar",
          "url": "core-ai-1.1.26.jar",
          "size": 380759,
          "sha512": "d4920b9c9ece52829ba6e3302f02094fc065464e265846b56cb44f8966325a66a47e20fa64ab85af467a48a7048341c4efa4ca87b5418ed1d13f566a2f208224",
          "sha256": "185614418490e029dd523e7a33dd8fc091c2740b75e20c8bbb7f6118c9dec70c",
          "sha1": "7e15950c87fb33c199847a17715f35fa52e5d351",
          "md5": "b67f0b44578087228abe8336d4ff778b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.26.jar",
          "url": "core-ai-1.1.26.jar",
          "size": 380759,
          "sha512": "d4920b9c9ece52829ba6e3302f02094fc065464e265846b56cb44f8966325a66a47e20fa64ab85af467a48a7048341c4efa4ca87b5418ed1d13f566a2f208224",
          "sha256": "185614418490e029dd523e7a33dd8fc091c2740b75e20c8bbb7f6118c9dec70c",
          "sha1": "7e15950c87fb33c199847a17715f35fa52e5d351",
          "md5": "b67f0b44578087228abe8336d4ff778b"
        }
      ]
    }
  ]
}
