{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.6.jar",
          "url": "core-ai-1.1.6.jar",
          "size": 353344,
          "sha512": "ab80c970dc828896a6de0039bd8ed60811fece3f7ff950079b077c9e894263dfeb7b3da58c7f8954b538c5b7a361e65d234782f4819c6286557196b6e96d69e0",
          "sha256": "5f5af8ae49c40ab5c4446f0a037f5323a83295250b6c0bba4fc0190fa8df990a",
          "sha1": "435c803ed82641d567ee775b0eb789c1e5544235",
          "md5": "7d2150970450038b7db451e9b37d3825"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.6.jar",
          "url": "core-ai-1.1.6.jar",
          "size": 353344,
          "sha512": "ab80c970dc828896a6de0039bd8ed60811fece3f7ff950079b077c9e894263dfeb7b3da58c7f8954b538c5b7a361e65d234782f4819c6286557196b6e96d69e0",
          "sha256": "5f5af8ae49c40ab5c4446f0a037f5323a83295250b6c0bba4fc0190fa8df990a",
          "sha1": "435c803ed82641d567ee775b0eb789c1e5544235",
          "md5": "7d2150970450038b7db451e9b37d3825"
        }
      ]
    }
  ]
}
