{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.43.jar",
          "url": "core-ai-1.1.43.jar",
          "size": 381354,
          "sha512": "dbc7446bf7a7400d6e6468d942a83e514f36d57e4f5f68387d891be58e92f72df0c631283827bfa74fde7a2dee7b25c9783d7eeb23296663f2df48f09490e507",
          "sha256": "cc83d10f52f3ebd9d7765fea4e529037af1bb03af87c9716e390b7a1fe875c85",
          "sha1": "a1c29caf34b16adfae9c5d8cf208cc9a0037b021",
          "md5": "d9fec09d97fc39524b82381ea61ea4b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.43.jar",
          "url": "core-ai-1.1.43.jar",
          "size": 381354,
          "sha512": "dbc7446bf7a7400d6e6468d942a83e514f36d57e4f5f68387d891be58e92f72df0c631283827bfa74fde7a2dee7b25c9783d7eeb23296663f2df48f09490e507",
          "sha256": "cc83d10f52f3ebd9d7765fea4e529037af1bb03af87c9716e390b7a1fe875c85",
          "sha1": "a1c29caf34b16adfae9c5d8cf208cc9a0037b021",
          "md5": "d9fec09d97fc39524b82381ea61ea4b7"
        }
      ]
    }
  ]
}
