{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.73",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.73.jar",
          "url": "core-ai-1.1.73.jar",
          "size": 417522,
          "sha512": "112d7b841657ff4b96e53e1d26bd0503bea31ccd7aa0b35f1a5969e36c40b6ec1468162017004ebfce6016a1f3dd4669f0ad71401d5ccaa8f49a7ac0307aad77",
          "sha256": "c9402b28918176635e75a6bea2e87804b36d3d1ec242de74b229764280e6dec4",
          "sha1": "13d15f6c5efaae462f065ca95eaf670ed7aefcb4",
          "md5": "9cf207d630c2c79c8b366b1b4c7eb421"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.73.jar",
          "url": "core-ai-1.1.73.jar",
          "size": 417522,
          "sha512": "112d7b841657ff4b96e53e1d26bd0503bea31ccd7aa0b35f1a5969e36c40b6ec1468162017004ebfce6016a1f3dd4669f0ad71401d5ccaa8f49a7ac0307aad77",
          "sha256": "c9402b28918176635e75a6bea2e87804b36d3d1ec242de74b229764280e6dec4",
          "sha1": "13d15f6c5efaae462f065ca95eaf670ed7aefcb4",
          "md5": "9cf207d630c2c79c8b366b1b4c7eb421"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.73-sources.jar",
          "url": "core-ai-1.1.73-sources.jar",
          "size": 174095,
          "sha512": "02fc6b19d328a49cab38c8f3da9f2f707c75751e0350f8f02575f16eaa8662e9e1f85b41d3d4f9c31154bb4b934decca3a9fa5a32410013cef1353a57979ed1d",
          "sha256": "8d65ba142a86e09a5d7c97015ed96c3581592da8758df42070e0fe4e69665f82",
          "sha1": "648df187b09cb7939d618fb9fb4f281ea37c26a3",
          "md5": "93d71864ceb26c72560720930c1e29e9"
        }
      ]
    }
  ]
}
