{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.5.jar",
          "url": "core-ai-1.1.5.jar",
          "size": 353045,
          "sha512": "18ffd3ba9c30bd4546d62c7a3bc0c5d1da4cd90bd52465693a6257fe429ad097bb2e74d2ceec60df30f6e92279ea886efae2a5f0d7f4d6d28e27167531ad0ebb",
          "sha256": "ce7171c734e90af9cd054906a4dc262809bcbb5821d06efd789c4f252ecb70f9",
          "sha1": "41111b2760ddfaf5f795c8eadc0aeb2be5446bcf",
          "md5": "c3696b446791ede0ef9eaf9d4fade9a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.5.jar",
          "url": "core-ai-1.1.5.jar",
          "size": 353045,
          "sha512": "18ffd3ba9c30bd4546d62c7a3bc0c5d1da4cd90bd52465693a6257fe429ad097bb2e74d2ceec60df30f6e92279ea886efae2a5f0d7f4d6d28e27167531ad0ebb",
          "sha256": "ce7171c734e90af9cd054906a4dc262809bcbb5821d06efd789c4f252ecb70f9",
          "sha1": "41111b2760ddfaf5f795c8eadc0aeb2be5446bcf",
          "md5": "c3696b446791ede0ef9eaf9d4fade9a1"
        }
      ]
    }
  ]
}
