{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.74",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.74.jar",
          "url": "core-ai-1.1.74.jar",
          "size": 417505,
          "sha512": "ba90eb6a785e7bdf43970d4e515f08018725b06d6f215e05887882b5a72db8f6946dd76454542de86b1fa1e2c3a3ca5bd2e2a16bb7aa4d9cd3aa7ca36ade3811",
          "sha256": "8d51b0f0d0581241a8cf56f8c8bba3c8d6d04c515a42a339b3a862aa6c4a62c2",
          "sha1": "9581eba1fb1a447d2bdcfafb18711b82ca038c23",
          "md5": "f06ab4739ae93dd459011865a634416d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.74.jar",
          "url": "core-ai-1.1.74.jar",
          "size": 417505,
          "sha512": "ba90eb6a785e7bdf43970d4e515f08018725b06d6f215e05887882b5a72db8f6946dd76454542de86b1fa1e2c3a3ca5bd2e2a16bb7aa4d9cd3aa7ca36ade3811",
          "sha256": "8d51b0f0d0581241a8cf56f8c8bba3c8d6d04c515a42a339b3a862aa6c4a62c2",
          "sha1": "9581eba1fb1a447d2bdcfafb18711b82ca038c23",
          "md5": "f06ab4739ae93dd459011865a634416d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.74-sources.jar",
          "url": "core-ai-1.1.74-sources.jar",
          "size": 174084,
          "sha512": "de720e1d08f3817ab4b7d74df274cdb9a6824bfb524ae7016f721f6dbe6b04dde24f018ac2db4f3b9f04bdc581e8a246dde6efcc84c6f2e4fc25485ad9ec7d4e",
          "sha256": "35515541c9a80fd2c9569d7301be17d689b44a00b9a80781dd3bf807083d23ef",
          "sha1": "20fd1ec51fc896e4854a4d6966be112bcb4aaf5a",
          "md5": "12311724c39a35b881b6be8800a638ef"
        }
      ]
    }
  ]
}
