{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.78",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.78.jar",
          "url": "core-ai-1.1.78.jar",
          "size": 416706,
          "sha512": "f369a09dfda430f090d01343160d135c9ca2fa5249e2b072eec5e5952516d0b9cdda8f317ca81664442cf0db120f0c5ac9ceaf867b0539a6b43c76e1e67e81e4",
          "sha256": "8ca44a3d4b554bb2af4de9d6b1b67bfb270fca2d058ba1e5547755dbab513827",
          "sha1": "5bfd2d27c2dc3585d082f7034f133a57b1ac088e",
          "md5": "51434cff00989894eefd6f5c1457093b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.78.jar",
          "url": "core-ai-1.1.78.jar",
          "size": 416706,
          "sha512": "f369a09dfda430f090d01343160d135c9ca2fa5249e2b072eec5e5952516d0b9cdda8f317ca81664442cf0db120f0c5ac9ceaf867b0539a6b43c76e1e67e81e4",
          "sha256": "8ca44a3d4b554bb2af4de9d6b1b67bfb270fca2d058ba1e5547755dbab513827",
          "sha1": "5bfd2d27c2dc3585d082f7034f133a57b1ac088e",
          "md5": "51434cff00989894eefd6f5c1457093b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.78-sources.jar",
          "url": "core-ai-1.1.78-sources.jar",
          "size": 174916,
          "sha512": "9e8fac43b283625c4c57d7c5e75af2b2a957bbb0c11e393b9f2fcdf08ed9a5500b4ce2c7dc47e2a92dce345ae16c2ffce0107cb903eeb5bcc2bf21f4403ce7b7",
          "sha256": "2512f18420a2c8888d7990aefa634d0b595bde0f25e3546d1d075840858aa934",
          "sha1": "dd8a52cdc7f4fe7121a5ba70a177a58ec0b47037",
          "md5": "443d9569e8fb3563961482f299a70c38"
        }
      ]
    }
  ]
}
