{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.25.jar",
          "url": "core-ai-1.1.25.jar",
          "size": 380661,
          "sha512": "2980972626d72a9328294667950f2aa718966d8f43dee23b6347d2993e90ad328f2dc21aef2ab331b67a90ab937ba51d75423b89bf48232d6b0ed7eef6a321de",
          "sha256": "246213159b03f18e9bbb0c037f628c314769ca948c0b30a33159ea97780ae746",
          "sha1": "13758f8dd3cdcff6bea8b42792555baa3b423306",
          "md5": "773c10c8702396ef057db17ceb5798d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.25.jar",
          "url": "core-ai-1.1.25.jar",
          "size": 380661,
          "sha512": "2980972626d72a9328294667950f2aa718966d8f43dee23b6347d2993e90ad328f2dc21aef2ab331b67a90ab937ba51d75423b89bf48232d6b0ed7eef6a321de",
          "sha256": "246213159b03f18e9bbb0c037f628c314769ca948c0b30a33159ea97780ae746",
          "sha1": "13758f8dd3cdcff6bea8b42792555baa3b423306",
          "md5": "773c10c8702396ef057db17ceb5798d5"
        }
      ]
    }
  ]
}
