{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.12.jar",
          "url": "core-ai-api-1.1.12.jar",
          "size": 33074,
          "sha512": "6c413399066ce32e10ec663704aaf817527b0b9ab45302395266f1429ac92b593c44cf1cd0d2e90d9e3e4cd24155eefed1b664d61c40036a3d207e998594d835",
          "sha256": "75c95bd7589da389a1ea0e4fe63b4bca500cce6f75712f55ef00c28b1cfc6af2",
          "sha1": "b40f595f267c933be27ec7f3eca276c74477d785",
          "md5": "f4a0b71edb1c64e4d2e5fae7c28bd277"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.1.12.jar",
          "url": "core-ai-api-1.1.12.jar",
          "size": 33074,
          "sha512": "6c413399066ce32e10ec663704aaf817527b0b9ab45302395266f1429ac92b593c44cf1cd0d2e90d9e3e4cd24155eefed1b664d61c40036a3d207e998594d835",
          "sha256": "75c95bd7589da389a1ea0e4fe63b4bca500cce6f75712f55ef00c28b1cfc6af2",
          "sha1": "b40f595f267c933be27ec7f3eca276c74477d785",
          "md5": "f4a0b71edb1c64e4d2e5fae7c28bd277"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.12-sources.jar",
          "url": "core-ai-api-1.1.12-sources.jar",
          "size": 21437,
          "sha512": "27e6bcbbd8ef55b925f6f32a972a2c41f47b5bbca31662e7cd5a3344df914639da049c001838879e30cf8e5aa764626feb4ebfd225c5a644da8def998843700d",
          "sha256": "847712a54d52493f94b9dd7b058dcfc237baa4e4b44fbe4024be9acb816a8a26",
          "sha1": "e40d288c08173ba2e2b3916815bd5e550ee87f7d",
          "md5": "48f8adccbeb44af9e5cbd6aed27e59eb"
        }
      ]
    }
  ]
}
