{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.61.jar",
          "url": "core-ai-1.1.61.jar",
          "size": 381687,
          "sha512": "f547cca79671e4f74a071c5b453d5ee47c1e7ca23e06e6123bb340c1a0fc4ebe5faa105449c7c26e5e8aa70187be7d8e4ef14552304a4ce3fc3fb30b0302e454",
          "sha256": "d5e6c83a0c929bea32a749130407e8b84b2c3447bec762f07e9e6727e73afe80",
          "sha1": "242a64a2bde2df7d39dfc7d345c849d7ac397659",
          "md5": "cc256b4cf1c1e208d69cb7d2a13fbdb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.9"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.61.jar",
          "url": "core-ai-1.1.61.jar",
          "size": 381687,
          "sha512": "f547cca79671e4f74a071c5b453d5ee47c1e7ca23e06e6123bb340c1a0fc4ebe5faa105449c7c26e5e8aa70187be7d8e4ef14552304a4ce3fc3fb30b0302e454",
          "sha256": "d5e6c83a0c929bea32a749130407e8b84b2c3447bec762f07e9e6727e73afe80",
          "sha1": "242a64a2bde2df7d39dfc7d345c849d7ac397659",
          "md5": "cc256b4cf1c1e208d69cb7d2a13fbdb6"
        }
      ]
    }
  ]
}
