{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.108",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.108.jar",
          "url": "core-ai-1.1.108.jar",
          "size": 713119,
          "sha512": "b97373ca1af9dd6123ca24d60802831c700682716b5ad24355eb43bb929839a4615e1fa5bd86c2f7b892d57aba7a51aea666ac9eab245b6c237993505f767f2e",
          "sha256": "d776f7ec02af2ba1a6a230117820e428788c863765b8b65d968e57994d6f7aa0",
          "sha1": "7e09876cd69381986cf1a291d8d43f036b84e949",
          "md5": "545dcf24ede9509a33fe934c3cfe008b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.108.jar",
          "url": "core-ai-1.1.108.jar",
          "size": 713119,
          "sha512": "b97373ca1af9dd6123ca24d60802831c700682716b5ad24355eb43bb929839a4615e1fa5bd86c2f7b892d57aba7a51aea666ac9eab245b6c237993505f767f2e",
          "sha256": "d776f7ec02af2ba1a6a230117820e428788c863765b8b65d968e57994d6f7aa0",
          "sha1": "7e09876cd69381986cf1a291d8d43f036b84e949",
          "md5": "545dcf24ede9509a33fe934c3cfe008b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.108-sources.jar",
          "url": "core-ai-1.1.108-sources.jar",
          "size": 336824,
          "sha512": "b6f4b50236f53b78aa6360edcb288ecc128fc0b79bd443ac9f7d98afd5fe6232062790f0b64dffc645e8b571e7f556dec2f1a341e63e0f74b044051a643c57fd",
          "sha256": "7db07703237ca7a2da0030439346f2440b66375e615152f388cceba0a18b4557",
          "sha1": "e28126ec361d29b137a81ca4c9c95bc08e36a925",
          "md5": "e88d3648d6e52428b9dc4bf9cb82db9b"
        }
      ]
    }
  ]
}
