{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.79.jar",
          "url": "core-ai-1.1.79.jar",
          "size": 416788,
          "sha512": "a6081b92fa8a2a51d67ae9ee0d0cdd5fbcc574b5610ff438bbdc4907baca56dc0c1ee6db77b8d9ef21082462914b2e360d7f7c86602091c0a36c1a0211498905",
          "sha256": "96ae039536992313e4ebd804625491feeb5d9d37189da46443fbe0645528790c",
          "sha1": "d6e165272745792d616e55e06391e3a255cf15b6",
          "md5": "f96b458cb4433fcf1633ac7997191e36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.79.jar",
          "url": "core-ai-1.1.79.jar",
          "size": 416788,
          "sha512": "a6081b92fa8a2a51d67ae9ee0d0cdd5fbcc574b5610ff438bbdc4907baca56dc0c1ee6db77b8d9ef21082462914b2e360d7f7c86602091c0a36c1a0211498905",
          "sha256": "96ae039536992313e4ebd804625491feeb5d9d37189da46443fbe0645528790c",
          "sha1": "d6e165272745792d616e55e06391e3a255cf15b6",
          "md5": "f96b458cb4433fcf1633ac7997191e36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.79-sources.jar",
          "url": "core-ai-1.1.79-sources.jar",
          "size": 174952,
          "sha512": "7a9f6174dd6055379b9032c30627fd0f354f2673a708a8eb78a1850508bd1733fdd8d173db78818b7cbabbae5715be90baeb6c898cede22d98228ed96081ace7",
          "sha256": "9b764cd83c092bf5b63ffcd861ebcc701eb8df391e38bbe1e0c08f53987eaff5",
          "sha1": "03d03ac7b6da424df8b86ccbec2131992bf06335",
          "md5": "c3d37ddf934e7e0fa2e1b4bc1dfccd3e"
        }
      ]
    }
  ]
}
