{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.54.jar",
          "url": "core-ai-1.1.54.jar",
          "size": 379714,
          "sha512": "dd97313779e46ba4989a089706ba2e20a44d77baa2bed65bd17d1322b09320226f7d26fc6f10d5318ea9a076c5aa8c4813f1036dc0d51e74a1e57f204877fc58",
          "sha256": "da70a131fe2c55a1c7a8847b74631ee330421f8b5865ef07e127bdd9375c0b11",
          "sha1": "fc539649fa8a3ff19f4b1bb03982e5771daecf7b",
          "md5": "23149d54f2aa6e08547d20a16704025b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.54.jar",
          "url": "core-ai-1.1.54.jar",
          "size": 379714,
          "sha512": "dd97313779e46ba4989a089706ba2e20a44d77baa2bed65bd17d1322b09320226f7d26fc6f10d5318ea9a076c5aa8c4813f1036dc0d51e74a1e57f204877fc58",
          "sha256": "da70a131fe2c55a1c7a8847b74631ee330421f8b5865ef07e127bdd9375c0b11",
          "sha1": "fc539649fa8a3ff19f4b1bb03982e5771daecf7b",
          "md5": "23149d54f2aa6e08547d20a16704025b"
        }
      ]
    }
  ]
}
