{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.37.jar",
          "url": "core-ai-1.1.37.jar",
          "size": 381080,
          "sha512": "339810add4ba81521e0339e886aa67573d02b17ab9fa4fcbabf6ca8734964ecaeca44842aa45087f14cb6d3deddcd55159f0d219eb782aa8545242348db788ca",
          "sha256": "832e906d60ef37eef9a1e9746c482bfaba144bbc91634dfb59e50d40561aaa61",
          "sha1": "5a4d74f5143e1e46f8ee5021b68556e7543ef877",
          "md5": "c44855cb132c980d26163c625cd2e083"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.37.jar",
          "url": "core-ai-1.1.37.jar",
          "size": 381080,
          "sha512": "339810add4ba81521e0339e886aa67573d02b17ab9fa4fcbabf6ca8734964ecaeca44842aa45087f14cb6d3deddcd55159f0d219eb782aa8545242348db788ca",
          "sha256": "832e906d60ef37eef9a1e9746c482bfaba144bbc91634dfb59e50d40561aaa61",
          "sha1": "5a4d74f5143e1e46f8ee5021b68556e7543ef877",
          "md5": "c44855cb132c980d26163c625cd2e083"
        }
      ]
    }
  ]
}
