{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.0.0.jar",
          "url": "litellm-library-1.0.0.jar",
          "size": 27092,
          "sha512": "541d20ae6f36e010d153f3a9949372d9dab8df1ab6c8585050eabde05202f8d1d1d2754fb1caa038b915ba45855c0d8ffc1923a9cf67215a1c3c956bbd89344d",
          "sha256": "58548c2bcef0a2d4d87f4e71a522058b312293613c06231d8ac41477b0788440",
          "sha1": "cf385696056ab9cc48df4fe1a714eb33ab87b3c0",
          "md5": "313ce57b3112f3d8d3f94e15a254ab33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.0.0.jar",
          "url": "litellm-library-1.0.0.jar",
          "size": 27092,
          "sha512": "541d20ae6f36e010d153f3a9949372d9dab8df1ab6c8585050eabde05202f8d1d1d2754fb1caa038b915ba45855c0d8ffc1923a9cf67215a1c3c956bbd89344d",
          "sha256": "58548c2bcef0a2d4d87f4e71a522058b312293613c06231d8ac41477b0788440",
          "sha1": "cf385696056ab9cc48df4fe1a714eb33ab87b3c0",
          "md5": "313ce57b3112f3d8d3f94e15a254ab33"
        }
      ]
    }
  ]
}
