{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.75",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.75.jar",
          "url": "core-ai-1.1.75.jar",
          "size": 418241,
          "sha512": "a100d65f54cf674e4ab67ff32193078ad16b1448a230033cdd21fd5f0f729a8a36c3004194c8bf90aa9721c1ded7967cab95d9d5d01300d69e0bc169173e77d1",
          "sha256": "ce36e69e692d1bf6cf965417a4bd8cf00fcbf3050acc8704165ed72ed4bf6d3e",
          "sha1": "c36c37e12c7b39ad9b5272a651888dd6f1ef8a21",
          "md5": "7fb83f72322214eb01e4a4e1d4252ace"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.75.jar",
          "url": "core-ai-1.1.75.jar",
          "size": 418241,
          "sha512": "a100d65f54cf674e4ab67ff32193078ad16b1448a230033cdd21fd5f0f729a8a36c3004194c8bf90aa9721c1ded7967cab95d9d5d01300d69e0bc169173e77d1",
          "sha256": "ce36e69e692d1bf6cf965417a4bd8cf00fcbf3050acc8704165ed72ed4bf6d3e",
          "sha1": "c36c37e12c7b39ad9b5272a651888dd6f1ef8a21",
          "md5": "7fb83f72322214eb01e4a4e1d4252ace"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.75-sources.jar",
          "url": "core-ai-1.1.75-sources.jar",
          "size": 174391,
          "sha512": "821a23fb67b8e05a743fa700e711d0bfb83a7a24d77a151c8af525d7dab7ca52dae0cf4061e1aff3ca6f837fcda9c6b4988bb5a3540eaa8586e591aed69ae265",
          "sha256": "3171d9a737e46a9a9ade9c5072078b305bb753c73f0ff867446745e3c33afc44",
          "sha1": "59c95ce80740b878a14fe247650cf25be5c7c008",
          "md5": "b72d63c362dc1b5ed3ff623fe38be5c5"
        }
      ]
    }
  ]
}
