{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 809961,
          "sha512": "53b8811d5c901bae31a65b42077de815188b747accb9f310e5c3a232643ef588a769634bf5afc5805e34bed2fdbcc6a661ae0cbb332d6f95e6810c802f6bd2b8",
          "sha256": "c862919365d93ceed5c833d5be8c58983e5e7ab3ae7565f9332fd7bfc222be80",
          "sha1": "4079271acf690a11f88374701eac2d931f704242",
          "md5": "e8ded3ea2bb660267055de5d86e670b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.3.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.23.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.47.2.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 809961,
          "sha512": "53b8811d5c901bae31a65b42077de815188b747accb9f310e5c3a232643ef588a769634bf5afc5805e34bed2fdbcc6a661ae0cbb332d6f95e6810c802f6bd2b8",
          "sha256": "c862919365d93ceed5c833d5be8c58983e5e7ab3ae7565f9332fd7bfc222be80",
          "sha1": "4079271acf690a11f88374701eac2d931f704242",
          "md5": "e8ded3ea2bb660267055de5d86e670b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "size": 367907,
          "sha512": "60078a3aabd4790b3cc1ca4e4bb8751e75d59dd34cc418edf6e4b90c9bccce12d7982db36f8c3e4d4b95623ea2fb5b5e7cc2d16f7c45851d1f0150c74bc8e56a",
          "sha256": "2e88d8de317cb181d6dfb5367de95eda3e7c0e36ba945a5d663f2c306e5e40ac",
          "sha1": "09347f64d1928ffe981c55d980f206098f582810",
          "md5": "6ec75b7f229a0d4341e20f5ac0e4f0c5"
        }
      ]
    }
  ]
}
