{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 842476,
          "sha512": "12c01de90a476cf634a9fa90bcadd9f52150ee509cb8fe50125860976b42e7840e5f79d73626234e92423182313526f5662cfbd530eab50bf49c75881baf679c",
          "sha256": "43fa3008e95b0fedb81e4a63e1f149f3c1b2b42119457cae6f06e7632f110faf",
          "sha1": "96ac35cf2fcb80d6c62aba26a4bbc6156abe1680",
          "md5": "606b6355904bec85c8317e1f68f5e5ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.3.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.23.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.47.2.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 842476,
          "sha512": "12c01de90a476cf634a9fa90bcadd9f52150ee509cb8fe50125860976b42e7840e5f79d73626234e92423182313526f5662cfbd530eab50bf49c75881baf679c",
          "sha256": "43fa3008e95b0fedb81e4a63e1f149f3c1b2b42119457cae6f06e7632f110faf",
          "sha1": "96ac35cf2fcb80d6c62aba26a4bbc6156abe1680",
          "md5": "606b6355904bec85c8317e1f68f5e5ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "size": 380106,
          "sha512": "03a2d013b1dbfbd201b6307b0669c502b27440d8c650bd8e57f0f7c3c54c3c2b49d6226135c8e45f9cf561e8c9a347da0dcfcee43e312f49c3d8db0f4c447b7f",
          "sha256": "1d0510f7debb15e43193ae7547cd07e439981729d30fb49955ada3d7c1569b58",
          "sha1": "b163798cad4e5b837d34b07eff22f33e0e090bff",
          "md5": "4ea91703ebc53dcefad548749d0f6118"
        }
      ]
    }
  ]
}
