{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-core",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-json-jackson2",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 1422554,
          "sha512": "6d6018167089f69928a31bf3cf0c7b7dd62614ba0ceadc167920f06308f08fc4617d00ee2f112eb59d1296f3f0130ffeecda8d1bbf4f36f738964da52a7b8d15",
          "sha256": "360c6e1eb80940fb1aff14dd51873a39fa0625c2251296d8649d319609063643",
          "sha1": "2048a31ef89d60e4049e6745c205b803de592b5e",
          "md5": "5c4cb54aa5f15288d81950e0d77cb2a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.3.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.23.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.30.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-core",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-json-jackson2",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 1422554,
          "sha512": "6d6018167089f69928a31bf3cf0c7b7dd62614ba0ceadc167920f06308f08fc4617d00ee2f112eb59d1296f3f0130ffeecda8d1bbf4f36f738964da52a7b8d15",
          "sha256": "360c6e1eb80940fb1aff14dd51873a39fa0625c2251296d8649d319609063643",
          "sha1": "2048a31ef89d60e4049e6745c205b803de592b5e",
          "md5": "5c4cb54aa5f15288d81950e0d77cb2a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "size": 668295,
          "sha512": "3da97e3841cae23a188408b4061dbcf00888ce83f99a91d78d49ccf978c73f89ebcdb43adea6b88c0c90b2c46bb2af73f582ab6f1e52026321e77cc6c9cf7b5d",
          "sha256": "03137e37b65b3825e0263b51af3c6a34ed2a50402585c7317bf61279297c1fcc",
          "sha1": "e8e6314f8831997fed0aa39c3a7464a947ed82de",
          "md5": "b0227abdd8151c0518deb80df439abd2"
        }
      ]
    }
  ]
}
