{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-core",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-json-jackson2",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 1422541,
          "sha512": "87336d509f5461deaac0d91cd3f7e86d3d53c55406ce36b4bb1bd680a70a70a89106c7508d270f1a5297ff00c13c751c3e387f2d2fd0178f979ad9dcd0573605",
          "sha256": "a9bdda7f915f09fca8185a18d7208cfcd4f94dbf8c768e4901cce7b95bb9482b",
          "sha1": "a38997caefafb977c953eb8a65861f912c43610f",
          "md5": "55f35ce14433ef6358b1550fe85548fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.3.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.23.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.30.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-core",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-json-jackson2",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 1422541,
          "sha512": "87336d509f5461deaac0d91cd3f7e86d3d53c55406ce36b4bb1bd680a70a70a89106c7508d270f1a5297ff00c13c751c3e387f2d2fd0178f979ad9dcd0573605",
          "sha256": "a9bdda7f915f09fca8185a18d7208cfcd4f94dbf8c768e4901cce7b95bb9482b",
          "sha1": "a38997caefafb977c953eb8a65861f912c43610f",
          "md5": "55f35ce14433ef6358b1550fe85548fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "size": 668478,
          "sha512": "1369a8eccc4c466bb5decd3412671aa0da50c008465ec0100317e080bfe253c5a8140555bfc2053e1ed9afe0298ab96a9069ad8500d9a764d5eed9affe0a84e4",
          "sha256": "6872083e6fe03c0fead762771b1cb0174d10958e05a9fcda060da7c9b35e8030",
          "sha1": "3b2969a0c572ac4310ecb6bad26938e7c0330cdd",
          "md5": "c6e47934c67e8c7835605edb7667acda"
        }
      ]
    }
  ]
}
