{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-core",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-json-jackson2",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 1415055,
          "sha512": "1d851063d264eab6ec052f103ba6f2e8e48221ac5f99effa5ca00638cd5ebd013ff424e839340d7583527f27246ca920af3065b0f74805999456aecd20cf34cc",
          "sha256": "1999e9b264c122e3b28befb4af571eae77e6ba37c885866d4a99b4addf460dc6",
          "sha1": "d28118b2ee84d0d0d3dbd225228fd4ef66a39d17",
          "md5": "7296113520b13b6372785a6b31277e77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.3.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.23.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.30.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-core",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp-json-jackson2",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 1415055,
          "sha512": "1d851063d264eab6ec052f103ba6f2e8e48221ac5f99effa5ca00638cd5ebd013ff424e839340d7583527f27246ca920af3065b0f74805999456aecd20cf34cc",
          "sha256": "1999e9b264c122e3b28befb4af571eae77e6ba37c885866d4a99b4addf460dc6",
          "sha1": "d28118b2ee84d0d0d3dbd225228fd4ef66a39d17",
          "md5": "7296113520b13b6372785a6b31277e77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "size": 665089,
          "sha512": "e719e2abbebba23299187d8a0faa33cd53098efa84dc343ad2e73a56a16657607e76734deeb5b4464b983506e3fdb3705ac6ca608684489b4e5fc8b554db22e9",
          "sha256": "30195264ca8373fcf78073e4a6a882b66eea0dadeca8ca94b2f9e485f23b14ea",
          "sha1": "4d78d1cf4ae2a143bb79498114b791651b4d1e2d",
          "md5": "fd815b1edb76e4e837a40ccda92183c8"
        }
      ]
    }
  ]
}
