{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 809887,
          "sha512": "36a2768ae8a0ee88f382694fccd80462696e2e5b9c633477a245e344343baeaa652b066f83437c59d7a430cdbbe93db4b1114be39f444b82bb644cf8a5ac37f8",
          "sha256": "cc972e8b3aef2d3a4bb31570773b3efa4a239d839c71009a5d5026405f000190",
          "sha1": "99bdf8a17e1bb3391972ada3b891b423a415dc35",
          "md5": "54507d6feb328a4378c77f3b860f6671"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.3.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.23.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.47.2.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT.jar",
          "url": "core-ai-1.3.0-SNAPSHOT.jar",
          "size": 809887,
          "sha512": "36a2768ae8a0ee88f382694fccd80462696e2e5b9c633477a245e344343baeaa652b066f83437c59d7a430cdbbe93db4b1114be39f444b82bb644cf8a5ac37f8",
          "sha256": "cc972e8b3aef2d3a4bb31570773b3efa4a239d839c71009a5d5026405f000190",
          "sha1": "99bdf8a17e1bb3391972ada3b891b423a415dc35",
          "md5": "54507d6feb328a4378c77f3b860f6671"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.3.0-SNAPSHOT-sources.jar",
          "size": 367946,
          "sha512": "168d2b57840c3ef0ccf8738621c7b879c8758fe9c2b783811eb600fa019652af2023fa4f51470a4fa8a469952ed6fef1568671c0b8cb759f8152115b419bf679",
          "sha256": "b40fbd99696aba877e28960fa32179c1f66bba8679966a3ce367c02203aa2154",
          "sha1": "fbc5fedd9399284ce2a799f13424a39f7ae544ef",
          "md5": "dbb3989c2ca8c1921d06c5b997940818"
        }
      ]
    }
  ]
}
