{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.66.jar",
          "url": "core-ai-1.1.66.jar",
          "size": 417045,
          "sha512": "7e0a7aaf56ee2ef99ec525e89321bf6c92f92c47d3e07769945ac6a821851e7e18c2bd011976223e38524527b06b1bde388757ca1f96f0e7f4fea8c4ac7ca13a",
          "sha256": "8015c48be253b63f495ad9716a47b828f04d6bfc3f8159d04fcc297b36c00925",
          "sha1": "d340b400e499b8bc6dca6ffbb602bd981d0f8e85",
          "md5": "6d719c131ae6bc9810e1b5d8677f7b6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.11"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.66.jar",
          "url": "core-ai-1.1.66.jar",
          "size": 417045,
          "sha512": "7e0a7aaf56ee2ef99ec525e89321bf6c92f92c47d3e07769945ac6a821851e7e18c2bd011976223e38524527b06b1bde388757ca1f96f0e7f4fea8c4ac7ca13a",
          "sha256": "8015c48be253b63f495ad9716a47b828f04d6bfc3f8159d04fcc297b36c00925",
          "sha1": "d340b400e499b8bc6dca6ffbb602bd981d0f8e85",
          "md5": "6d719c131ae6bc9810e1b5d8677f7b6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.66-sources.jar",
          "url": "core-ai-1.1.66-sources.jar",
          "size": 173816,
          "sha512": "4cd59ddc19bef6052e1a2af90ffbb78710f884d45efed34e802be566dc34bd18aa6c5b6be20a9cd1618fc8ed38ea149c66e722b12ca47304e9ebe66e68570fbe",
          "sha256": "4c66d9df9655f32d892bee34c9445e1bdde5f186dfaa484e26cead736cd824a2",
          "sha1": "5ca2dd7dfd782b3444f8e454912d72a547802fab",
          "md5": "b48cfc2bedc8dbe61cf5756038e6f672"
        }
      ]
    }
  ]
}
