{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-1.2.0-SNAPSHOT.jar",
          "size": 736867,
          "sha512": "f6eca44ffba4e6fc781f6ab7b013341d36034b3f89cfc6e8dee87e1b3e9303055299fdb76df050b51efc9fd45be06a31b96ae7a708395a7882541ee958bfe512",
          "sha256": "01452c7e422451a31a6d2a0f491731bbfb0c2309ccc01b48258d82d5954eec25",
          "sha1": "4f39de31df849e94d40f9fe8d5f197cf1f941d74",
          "md5": "d6516bf45b6541df65b0208ab826aecf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.2.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.47.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-1.2.0-SNAPSHOT.jar",
          "size": 736867,
          "sha512": "f6eca44ffba4e6fc781f6ab7b013341d36034b3f89cfc6e8dee87e1b3e9303055299fdb76df050b51efc9fd45be06a31b96ae7a708395a7882541ee958bfe512",
          "sha256": "01452c7e422451a31a6d2a0f491731bbfb0c2309ccc01b48258d82d5954eec25",
          "sha1": "4f39de31df849e94d40f9fe8d5f197cf1f941d74",
          "md5": "d6516bf45b6541df65b0208ab826aecf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.2.0-SNAPSHOT-sources.jar",
          "size": 336651,
          "sha512": "18d964aae5a648dce4fa1beb758df136e94f627d82624b413dd6f1668b6db8af45f7ba9295d7da27a7ea1d115f6e17fedfa70ec78109b33d7955a601d60ade04",
          "sha256": "1ec68df46f9010ba6ba26f1e2261f159bb0b1d8571a240108c0cec12f9094698",
          "sha1": "b2c71b6c3030dab5b9e1b93d1a45491b8a37f580",
          "md5": "b4a53c775724a57c6479e45401d54f55"
        }
      ]
    }
  ]
}
