{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-1.2.0-SNAPSHOT.jar",
          "size": 719606,
          "sha512": "4c0216fa4a777204c704cf359f428eef20aebf5902e9102050618b1701ad187e9d9ac4d17c21cd5e8fd809d480ab038ee345ebf9fbc0d86f94eddda3050d3d12",
          "sha256": "1993e1c916fc8e518427af564a2243c471d2585d68bd34600646f09b1efe8b93",
          "sha1": "5093887f76bfa4337ded3e8ba002676c82221636",
          "md5": "37043fa565171da5819701cd82cf6858"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.2.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-1.2.0-SNAPSHOT.jar",
          "size": 719606,
          "sha512": "4c0216fa4a777204c704cf359f428eef20aebf5902e9102050618b1701ad187e9d9ac4d17c21cd5e8fd809d480ab038ee345ebf9fbc0d86f94eddda3050d3d12",
          "sha256": "1993e1c916fc8e518427af564a2243c471d2585d68bd34600646f09b1efe8b93",
          "sha1": "5093887f76bfa4337ded3e8ba002676c82221636",
          "md5": "37043fa565171da5819701cd82cf6858"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.2.0-SNAPSHOT-sources.jar",
          "size": 335378,
          "sha512": "7e3556436a1bb025b4d26c65768c72e978c811086d9a82b9169d06461bc8f506b36b3de584fa0247552b8e7df8282982357b45384103ed5a274eb531a39b6ddf",
          "sha256": "1beead7fef3d790e34af3faf08627c70c39a9fe1f0cee9997788763425154d56",
          "sha1": "e1d7ff033a7e0e7cf5a5b0623c5fd02aede5b467",
          "md5": "034d76f796510268fb50d23d4b465c4b"
        }
      ]
    }
  ]
}
