{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-1.2.0-SNAPSHOT.jar",
          "size": 712537,
          "sha512": "25858d0c49c9a2a08eaeba324e0a08a32d3a77975bb3ba63b668113a13851e8c6724cf04a82007264ec0750aecbc24119038049a28b22ffd59eda43c65d5c937",
          "sha256": "aaa84025448df376906b7aa57f81821741205ff75d72fa974ae2b300bdc416c8",
          "sha1": "ded9b4669ace080ddedbbc9dcda24204ab5a4104",
          "md5": "78ab381f1259b6a0215727d58ab06ca9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.2.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-1.2.0-SNAPSHOT.jar",
          "size": 712537,
          "sha512": "25858d0c49c9a2a08eaeba324e0a08a32d3a77975bb3ba63b668113a13851e8c6724cf04a82007264ec0750aecbc24119038049a28b22ffd59eda43c65d5c937",
          "sha256": "aaa84025448df376906b7aa57f81821741205ff75d72fa974ae2b300bdc416c8",
          "sha1": "ded9b4669ace080ddedbbc9dcda24204ab5a4104",
          "md5": "78ab381f1259b6a0215727d58ab06ca9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.2.0-SNAPSHOT-sources.jar",
          "size": 334403,
          "sha512": "c7bebb5bae154a8002af6622d3b04bb932f8f6016d8a3b3dd1ff5ed50494a1dcc05692b39450d6fffe20a05cc88f4465a06f4ed3e768d6eb4514e5c175e48051",
          "sha256": "b6ba390dc6cccf8a6ae3ce3027a4d0955f7553c5eb11254b6df42b226fbd85a5",
          "sha1": "28395d712893ab7d1bc4cf2df1b2cdc0e6e820e6",
          "md5": "c62f78ad4277abd4c67677f98b0511de"
        }
      ]
    }
  ]
}
