{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-1.2.0-SNAPSHOT.jar",
          "size": 733056,
          "sha512": "1c8e58cf64a5beac6637f4e2787af7b76abdeea2ad5b636e91a28ab71f7713f4acaed7e941fa59bdc1726b259bf54ca59fbe96e61b86801e5c4ca83cf0d97c05",
          "sha256": "2318c68d3b42c96c801670e653f6619f12b99be7e49442bd9481c3d3fa4a84f3",
          "sha1": "6d1a8f401afadcf31002441b0d64a2b5ac6e437b",
          "md5": "94f088c97ef09f23a522d3b3dfaddad9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.2.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.47.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-1.2.0-SNAPSHOT.jar",
          "size": 733056,
          "sha512": "1c8e58cf64a5beac6637f4e2787af7b76abdeea2ad5b636e91a28ab71f7713f4acaed7e941fa59bdc1726b259bf54ca59fbe96e61b86801e5c4ca83cf0d97c05",
          "sha256": "2318c68d3b42c96c801670e653f6619f12b99be7e49442bd9481c3d3fa4a84f3",
          "sha1": "6d1a8f401afadcf31002441b0d64a2b5ac6e437b",
          "md5": "94f088c97ef09f23a522d3b3dfaddad9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.2.0-SNAPSHOT-sources.jar",
          "url": "core-ai-1.2.0-SNAPSHOT-sources.jar",
          "size": 335328,
          "sha512": "99378afd78009ea2128b519ad5c6bd1ce99a27d18f508fb27a8159785e796b5002dda9092001510c4c512b1c7b92e184c12ab1e282b603c8b33b09fd3d705ef4",
          "sha256": "4f191cfaa5d6a4739359f17191133438d653131f24a4e5e1ac0762c84e3db79a",
          "sha1": "578d272716db678355ec75daa0764ed9d72fad6c",
          "md5": "f344427321c35ec0af8f41885f147cd3"
        }
      ]
    }
  ]
}
