{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.84",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.84.jar",
          "url": "core-ai-1.1.84.jar",
          "size": 418267,
          "sha512": "557623dcfb9995b2476fceda105e8b6a7a035284f30668eb919a5c0011fc6aa65e0a48555f6aca8711b53ebb7b1783178d3ed34dd157db39ac47075c48912e76",
          "sha256": "02f96296e1920627eaebd238095691af01af21f78a9920edcc67ebef44ac9220",
          "sha1": "616a07c1cefbb9ff0565b339b2c0fe6271c2baa6",
          "md5": "7b50fe549b9b9d1c127dbf8f812726f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.84.jar",
          "url": "core-ai-1.1.84.jar",
          "size": 418267,
          "sha512": "557623dcfb9995b2476fceda105e8b6a7a035284f30668eb919a5c0011fc6aa65e0a48555f6aca8711b53ebb7b1783178d3ed34dd157db39ac47075c48912e76",
          "sha256": "02f96296e1920627eaebd238095691af01af21f78a9920edcc67ebef44ac9220",
          "sha1": "616a07c1cefbb9ff0565b339b2c0fe6271c2baa6",
          "md5": "7b50fe549b9b9d1c127dbf8f812726f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.84-sources.jar",
          "url": "core-ai-1.1.84-sources.jar",
          "size": 175445,
          "sha512": "66d270668db55be496dcb8ad72d8340fc50597e4dd05f4c0089ac56f1f197b043ddf1f53f500802f9f77af426e19e6d78fd731ef82f8dd1669b947324c8f0118",
          "sha256": "69c2dedf1eca0774de82c81fc03b7a096f0debf1008e252f0bec9ada6e4f97e8",
          "sha1": "35b5016198c65e7e8760f57bfdf5a06412a54884",
          "md5": "e55118dcb849ac6e898df58edf76587e"
        }
      ]
    }
  ]
}
