{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.44.jar",
          "url": "core-ai-1.1.44.jar",
          "size": 381578,
          "sha512": "4e236220cff79d5c5891e43ac5991c56fe03cf6b21670d6619d0018fb9498995ec1e07b97aa5c39a53653eaa1b5e74a80a70e78ed1a3e31f2002fe28196e2703",
          "sha256": "5db22db51798a6abd5616146b3d3cc64432f232b5fba1d9355aaea0211e3b38a",
          "sha1": "9778a42d24148c01eddf75ce92d15520122df732",
          "md5": "e8fd0242b01d7ff983740c5a0262e68c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.44.jar",
          "url": "core-ai-1.1.44.jar",
          "size": 381578,
          "sha512": "4e236220cff79d5c5891e43ac5991c56fe03cf6b21670d6619d0018fb9498995ec1e07b97aa5c39a53653eaa1b5e74a80a70e78ed1a3e31f2002fe28196e2703",
          "sha256": "5db22db51798a6abd5616146b3d3cc64432f232b5fba1d9355aaea0211e3b38a",
          "sha1": "9778a42d24148c01eddf75ce92d15520122df732",
          "md5": "e8fd0242b01d7ff983740c5a0262e68c"
        }
      ]
    }
  ]
}
