{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.18.jar",
          "url": "core-ai-1.1.18.jar",
          "size": 377165,
          "sha512": "f187cd5c598b41d232d614a7cfd5f8dd4a2d8e58e7f7d2935fe7714f9f246b6f07612b4909428ba2e6b7274946b7bc2d04255b1b852941ad7e5ebf5529d9b33f",
          "sha256": "818c3639de61a405f1a77b90717f52eda9550e36a4be2fe785056b38891d0f6b",
          "sha1": "266fc99cc39752df38c691b01b4058fb378e9fc7",
          "md5": "b23f35bc4227d9a3660227d599293f12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.18.jar",
          "url": "core-ai-1.1.18.jar",
          "size": 377165,
          "sha512": "f187cd5c598b41d232d614a7cfd5f8dd4a2d8e58e7f7d2935fe7714f9f246b6f07612b4909428ba2e6b7274946b7bc2d04255b1b852941ad7e5ebf5529d9b33f",
          "sha256": "818c3639de61a405f1a77b90717f52eda9550e36a4be2fe785056b38891d0f6b",
          "sha1": "266fc99cc39752df38c691b01b4058fb378e9fc7",
          "md5": "b23f35bc4227d9a3660227d599293f12"
        }
      ]
    }
  ]
}
