{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.1.11.jar",
          "url": "litellm-library-1.1.11.jar",
          "size": 28886,
          "sha512": "c31c862670fab07d0a8d450a0304df76d68cab8308c355be0702d49604f448e0e118f9380690d2dcaefcda8b59cb1516ae66771c5fd8db613c48b476de5f863f",
          "sha256": "69ce8adce9933293af67a6208a2e271d29c3d28a3ff696b6cc52386bd9f80fa1",
          "sha1": "475f29cb2ec6d906998546ff565bd670b4e113b7",
          "md5": "28a4d7e2ec94e0557cd156389fd3d0bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.1.11.jar",
          "url": "litellm-library-1.1.11.jar",
          "size": 28886,
          "sha512": "c31c862670fab07d0a8d450a0304df76d68cab8308c355be0702d49604f448e0e118f9380690d2dcaefcda8b59cb1516ae66771c5fd8db613c48b476de5f863f",
          "sha256": "69ce8adce9933293af67a6208a2e271d29c3d28a3ff696b6cc52386bd9f80fa1",
          "sha1": "475f29cb2ec6d906998546ff565bd670b4e113b7",
          "md5": "28a4d7e2ec94e0557cd156389fd3d0bf"
        }
      ]
    }
  ]
}
