{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.16.jar",
          "url": "core-ai-1.1.16.jar",
          "size": 377103,
          "sha512": "bc8eedae84f0e03e393b7f55422363ea0face8d67c2420a4f04b9d5274273692295f57ab00136e9ce57801f913b40929e7a1a617f63e1080aa35a6e8fa5e592b",
          "sha256": "67126ca677bd227baca60a4ecd8733a5eeabd4b15c51920e379a3c61d96c35ad",
          "sha1": "fc7df5141a0276a5119ecafad1fd6bcf6dc9521b",
          "md5": "98d58c217f8a97376ddf76dc523fd7c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.16.jar",
          "url": "core-ai-1.1.16.jar",
          "size": 377103,
          "sha512": "bc8eedae84f0e03e393b7f55422363ea0face8d67c2420a4f04b9d5274273692295f57ab00136e9ce57801f913b40929e7a1a617f63e1080aa35a6e8fa5e592b",
          "sha256": "67126ca677bd227baca60a4ecd8733a5eeabd4b15c51920e379a3c61d96c35ad",
          "sha1": "fc7df5141a0276a5119ecafad1fd6bcf6dc9521b",
          "md5": "98d58c217f8a97376ddf76dc523fd7c5"
        }
      ]
    }
  ]
}
