{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "operation-assistant-service-interface",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "operation-assistant-service-interface-1.0.0.jar",
          "url": "operation-assistant-service-interface-1.0.0.jar",
          "size": 10806,
          "sha512": "035051656d578c1f478aaca5a93c85679cd2150c30a3c776e6ba4cabbce53a7a2e42c53d37f79e4925bec12e26675d06496d4be8599e0e5767c1c9e13cd2d44e",
          "sha256": "f9f106ef88ea6c7e323a9f4d85fa5655e46b2376c1bd91438abd1dc677822b45",
          "sha1": "31627455f410e84c4aac455009ea816ba9294812",
          "md5": "609817b2f033cafb77bb5c20cc9058e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "operation-assistant-service-interface-1.0.0.jar",
          "url": "operation-assistant-service-interface-1.0.0.jar",
          "size": 10806,
          "sha512": "035051656d578c1f478aaca5a93c85679cd2150c30a3c776e6ba4cabbce53a7a2e42c53d37f79e4925bec12e26675d06496d4be8599e0e5767c1c9e13cd2d44e",
          "sha256": "f9f106ef88ea6c7e323a9f4d85fa5655e46b2376c1bd91438abd1dc677822b45",
          "sha1": "31627455f410e84c4aac455009ea816ba9294812",
          "md5": "609817b2f033cafb77bb5c20cc9058e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-assistant-service-interface-1.0.0-sources.jar",
          "url": "operation-assistant-service-interface-1.0.0-sources.jar",
          "size": 6812,
          "sha512": "fc7e98d0e83082e965c2d12de91186aaf59e7c467cc76fbb5d04ac91dca3bc3639c4978e75c659bc500690a54d725990a506c53ed8a0dce9fcea6470584d7afe",
          "sha256": "3a6c6c25da627a79d902ad1d789efcd3fc75ad8b14be9ddcbb7a81e992318cf7",
          "sha1": "c8f32398faaa2b75b3db774e6555b8a49160f069",
          "md5": "9271b1444ddbc4220bb03b7a746d69be"
        }
      ]
    }
  ]
}
