{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.8.jar",
          "url": "core-ai-1.1.8.jar",
          "size": 353687,
          "sha512": "192e8b413f1288b272aeaa095507d701c23f35eead30857cfcea29028e1dcc63ffd109877351f3396ccda50a2f36872e0be4ad6099e7e124675c975d5a62386e",
          "sha256": "fbb9c0ff503d9d4aa1fc1adbbc8ddb3f0a12f0517d5c745d80cb63c3cafb7363",
          "sha1": "d97e4f06480a39c5a7d938486d3ad30564325515",
          "md5": "5919773cb034d59ddb27b79673c0c4b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.8.jar",
          "url": "core-ai-1.1.8.jar",
          "size": 353687,
          "sha512": "192e8b413f1288b272aeaa095507d701c23f35eead30857cfcea29028e1dcc63ffd109877351f3396ccda50a2f36872e0be4ad6099e7e124675c975d5a62386e",
          "sha256": "fbb9c0ff503d9d4aa1fc1adbbc8ddb3f0a12f0517d5c745d80cb63c3cafb7363",
          "sha1": "d97e4f06480a39c5a7d938486d3ad30564325515",
          "md5": "5919773cb034d59ddb27b79673c0c4b9"
        }
      ]
    }
  ]
}
