{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.106",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.106.jar",
          "url": "core-ai-1.1.106.jar",
          "size": 712703,
          "sha512": "e767abc33645af85485ed301d91a041c42209003943a428c3c8216e614b616fea215d2a6d156a02ab51b15c4c0b0deadceb932cc03c53ec436d9c44d5ded03c1",
          "sha256": "4f0fc73616e454923e39c8c8af62012493542287b20fbf358314c2f8021ea3c6",
          "sha1": "4e1f88f629305e4070babbd7590a5b3310c11c36",
          "md5": "6054498c97b3b0592f6326302e3847a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.106.jar",
          "url": "core-ai-1.1.106.jar",
          "size": 712703,
          "sha512": "e767abc33645af85485ed301d91a041c42209003943a428c3c8216e614b616fea215d2a6d156a02ab51b15c4c0b0deadceb932cc03c53ec436d9c44d5ded03c1",
          "sha256": "4f0fc73616e454923e39c8c8af62012493542287b20fbf358314c2f8021ea3c6",
          "sha1": "4e1f88f629305e4070babbd7590a5b3310c11c36",
          "md5": "6054498c97b3b0592f6326302e3847a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.106-sources.jar",
          "url": "core-ai-1.1.106-sources.jar",
          "size": 336478,
          "sha512": "36e9e67cf5c81eaef6f149300e8c18d62eb985e325014502d3eae150a1c5cb38d33327b43f4b43e83e5541c125bf9656ba37a419bdf8e072be29a884bedf947d",
          "sha256": "588dbbfd880606a1366553f1dd1d0de3e4745ddfe708faf2ef4cc7eefd908152",
          "sha1": "70912b288f9ef01b59074e2b0e8001216ed47e81",
          "md5": "9ea88d154deae61bf7a549b9eecf6737"
        }
      ]
    }
  ]
}
