{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "size": 37931,
          "sha512": "986aa5a86bd93e9f46d0fd37ea854e818de9578ca91e59385dd30ad90eec61220919b09f69192149d259eb8e59289494b135c45002c8508a5117af2d65f8cec7",
          "sha256": "c8f113c79b147f59646decdd8c41df1c80bcfddf6323e938a968534b1435dcf6",
          "sha1": "c2be5361f96b07accaafb28dd4d9f0986d5fc7ff",
          "md5": "95ca307a6d665fecb91fc0302662c730"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "size": 37931,
          "sha512": "986aa5a86bd93e9f46d0fd37ea854e818de9578ca91e59385dd30ad90eec61220919b09f69192149d259eb8e59289494b135c45002c8508a5117af2d65f8cec7",
          "sha256": "c8f113c79b147f59646decdd8c41df1c80bcfddf6323e938a968534b1435dcf6",
          "sha1": "c2be5361f96b07accaafb28dd4d9f0986d5fc7ff",
          "md5": "95ca307a6d665fecb91fc0302662c730"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT-sources.jar",
          "size": 22031,
          "sha512": "afb60424303486bd8ff8ce7940ea5177ad41a02b015a4a920371ea05cc105a849cb8a03bc66ad9b1e523689fcc85d0030f5e725d2dcc1836fab919602cbb27c3",
          "sha256": "246710a2f859de447fb60077a7bdb897769ca8c013460f1687f209cbcb17cec5",
          "sha1": "5432dd6d81a8477235c27323c7f9baf149b8dde8",
          "md5": "1dd3ba2932ec4ec479d2377a0b3dd213"
        }
      ]
    }
  ]
}
