{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "size": 37971,
          "sha512": "dc2b9ffc802ac9c307a9eb3fbecd16499b856adb6753b874f79e4fbb1d3241c908e1445749dcb3706a56331b89fef37db658d4fbd066e2764a6758253a861f12",
          "sha256": "a22b6e95d87fd70cff30f2f114529e1624379ce84fe6dc7d13c3f72e715ff83f",
          "sha1": "bed21e1933f5f8bf0f11fdc144b5f9c923c024e0",
          "md5": "cea581531188441878dfdb2cf101c0c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "size": 37971,
          "sha512": "dc2b9ffc802ac9c307a9eb3fbecd16499b856adb6753b874f79e4fbb1d3241c908e1445749dcb3706a56331b89fef37db658d4fbd066e2764a6758253a861f12",
          "sha256": "a22b6e95d87fd70cff30f2f114529e1624379ce84fe6dc7d13c3f72e715ff83f",
          "sha1": "bed21e1933f5f8bf0f11fdc144b5f9c923c024e0",
          "md5": "cea581531188441878dfdb2cf101c0c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT-sources.jar",
          "size": 22043,
          "sha512": "91b4e72ba30564dbc5b27e7a93963d7fbb37a8b4ee71c90ddf3ee119dd94ca5dc7591f2da742d88ea835ae00ae646b7f01648a2e0a643262f86fb2a5eb8c4312",
          "sha256": "5a8dac28d9f68048a17a6195c2c1d770fc15fdbc3b071d7e53e7ec69e6ee013b",
          "sha1": "3f280a6b44097bee671c50c0e3a984f0ae056c16",
          "md5": "73046b7c00df97df5aeee06af6556f67"
        }
      ]
    }
  ]
}
