{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "size": 37960,
          "sha512": "fc66e80f3a0bc17ae1879ba0075edd4d671b81c6da252ccd8da0d173324fabeebe3b6e3a0ae7e4a85ccecc6a1b5bf3fa128f445e1b789745049003827d025974",
          "sha256": "f5880421a7b207179053ca4ca12bbc83b867aaeecd77a99795daf8ee3b96871b",
          "sha1": "fb5f3cf3455b1400fa58aac145d146f7517428b3",
          "md5": "91c2228771bb512558189608892f8323"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT.jar",
          "size": 37960,
          "sha512": "fc66e80f3a0bc17ae1879ba0075edd4d671b81c6da252ccd8da0d173324fabeebe3b6e3a0ae7e4a85ccecc6a1b5bf3fa128f445e1b789745049003827d025974",
          "sha256": "f5880421a7b207179053ca4ca12bbc83b867aaeecd77a99795daf8ee3b96871b",
          "sha1": "fb5f3cf3455b1400fa58aac145d146f7517428b3",
          "md5": "91c2228771bb512558189608892f8323"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.2.0-SNAPSHOT-sources.jar",
          "url": "core-ai-api-1.2.0-SNAPSHOT-sources.jar",
          "size": 21665,
          "sha512": "5717796ec5cf29c69d8071b1816b495cb25cfb0a3b5cb94804eacc1f2293f2423e134cd66b8ac6809f65d6f4cedce19a7338a160c5512a2a0e880938ad76e394",
          "sha256": "7f16b859ebdf2c1e4ce1f1b911d231e1550b4d318f05d66345b1ec1af4220154",
          "sha1": "f539c3b395bc919db47d93851d9b6e7b0da48365",
          "md5": "332053b421e8994fa3ee293d09e557e1"
        }
      ]
    }
  ]
}
