{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-cli",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-cli-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-cli-1.0.0-SNAPSHOT.jar",
          "size": 86384,
          "sha512": "8138b79091311b938afb18c958e056931c811d65037639ac0a0f35fe9d59cee5edddd1c19ae4363df8cbe2053e8e1917f1ccaf10253044d8598c456aa740e56f",
          "sha256": "aacb5497e5445e82609f307aaebecfa561129aa5e3e9e5fbeb6740e0079c37b9",
          "sha1": "464ceea07c6d03e36ba0081422634b0bd758c04a",
          "md5": "b93486b0d63f9f04a91fa548f648c8c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai",
          "version": {
            "requires": "1.3.0-SNAPSHOT"
          }
        },
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.3.0-SNAPSHOT"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal",
          "version": {
            "requires": "3.26.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.26.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-style",
          "version": {
            "requires": "3.26.1"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-cli-1.0.0-SNAPSHOT.jar",
          "url": "core-ai-cli-1.0.0-SNAPSHOT.jar",
          "size": 86384,
          "sha512": "8138b79091311b938afb18c958e056931c811d65037639ac0a0f35fe9d59cee5edddd1c19ae4363df8cbe2053e8e1917f1ccaf10253044d8598c456aa740e56f",
          "sha256": "aacb5497e5445e82609f307aaebecfa561129aa5e3e9e5fbeb6740e0079c37b9",
          "sha1": "464ceea07c6d03e36ba0081422634b0bd758c04a",
          "md5": "b93486b0d63f9f04a91fa548f648c8c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-cli-1.0.0-SNAPSHOT-sources.jar",
          "url": "core-ai-cli-1.0.0-SNAPSHOT-sources.jar",
          "size": 38170,
          "sha512": "555cd69a5c02a8e25d8ce643e07d0d751690d0b04c0d28d1f04d7d6da7d7834d77df28629d7b2d128ec9e28ed0414ff7d3336bc168fd1142655b25de8aff145e",
          "sha256": "1dd44e6ceaada60a671a7e86285a63a7dc11d071be95b4d6a4af7ede721eae61",
          "sha1": "a6bcb1a001440f11a9025a381bb5748a0c68c115",
          "md5": "1c30fb4d5525736f86f14063c81b5e8e"
        }
      ]
    }
  ]
}
