{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.21.jar",
          "url": "core-ai-1.1.21.jar",
          "size": 377239,
          "sha512": "722306edbbab5367629aebd510bbff9913e97ea8967715f461c2b160c01571ead9698cd7029c7543d24b61548a7c81e71b3ce928f2bcacbfdfc29bacfe182510",
          "sha256": "72c762f2d37206ebce3ca547b4fe252099563f077236d3404b8218479fa74e04",
          "sha1": "6198bcd48a8d34741d958ca4e050e2621feb8dfd",
          "md5": "ee5b29f35802aae6d41ac56575b20fe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.21.jar",
          "url": "core-ai-1.1.21.jar",
          "size": 377239,
          "sha512": "722306edbbab5367629aebd510bbff9913e97ea8967715f461c2b160c01571ead9698cd7029c7543d24b61548a7c81e71b3ce928f2bcacbfdfc29bacfe182510",
          "sha256": "72c762f2d37206ebce3ca547b4fe252099563f077236d3404b8218479fa74e04",
          "sha1": "6198bcd48a8d34741d958ca4e050e2621feb8dfd",
          "md5": "ee5b29f35802aae6d41ac56575b20fe3"
        }
      ]
    }
  ]
}
