{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.50.jar",
          "url": "core-ai-1.1.50.jar",
          "size": 385998,
          "sha512": "72a9b148f041ad080723227a5f6e70fd2589e90d193b758df9b791aebafe5447e70da0a358de9b9f9908a061ed87086c251f1e6fbe002645c895d541a307fb24",
          "sha256": "b88290cbb4a6fa03a902d9f1cd852eac43fb6f67d34480b9f0baa07f057612be",
          "sha1": "5694756e868773081f3b6b376aa334a616425892",
          "md5": "9a0a35178e718aa5fc2b88fbc4ecebca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.11"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.50.jar",
          "url": "core-ai-1.1.50.jar",
          "size": 385998,
          "sha512": "72a9b148f041ad080723227a5f6e70fd2589e90d193b758df9b791aebafe5447e70da0a358de9b9f9908a061ed87086c251f1e6fbe002645c895d541a307fb24",
          "sha256": "b88290cbb4a6fa03a902d9f1cd852eac43fb6f67d34480b9f0baa07f057612be",
          "sha1": "5694756e868773081f3b6b376aa334a616425892",
          "md5": "9a0a35178e718aa5fc2b88fbc4ecebca"
        }
      ]
    }
  ]
}
