{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.48.jar",
          "url": "core-ai-1.1.48.jar",
          "size": 383908,
          "sha512": "0b60cf5790502c80957bb448c8ebd7e2b84b06959188b335d5165dffc24a5ee5c1623b00c0bb7dc6cea1fa4270134d8dd97d36836455b18fc6e13c850517c813",
          "sha256": "39dbb0058b2a6b3be7d1d1024d672d22af8c5ac0f384b1c05a57b3c4887a6d4a",
          "sha1": "47bcae91da883f6ffcca495855320e7ea83b94fe",
          "md5": "be6799ec0e866cfb7725dd7ec06f2ce5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.9"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.48.jar",
          "url": "core-ai-1.1.48.jar",
          "size": 383908,
          "sha512": "0b60cf5790502c80957bb448c8ebd7e2b84b06959188b335d5165dffc24a5ee5c1623b00c0bb7dc6cea1fa4270134d8dd97d36836455b18fc6e13c850517c813",
          "sha256": "39dbb0058b2a6b3be7d1d1024d672d22af8c5ac0f384b1c05a57b3c4887a6d4a",
          "sha1": "47bcae91da883f6ffcca495855320e7ea83b94fe",
          "md5": "be6799ec0e866cfb7725dd7ec06f2ce5"
        }
      ]
    }
  ]
}
