{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "agent-service-interface",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "agent-service-interface-1.0.1.jar",
          "url": "agent-service-interface-1.0.1.jar",
          "size": 3285,
          "sha512": "ec4e2b3da84c2970aa13133e12c2e300b7dbb83731df8971a2a9a6656dddffa3a793b86298f6c0126486f9f2110e4c39849e838474d630c7427a59905da3fa36",
          "sha256": "17fa982dc56dd8d4dfb36b43c552957a9479a71ad3f6eff44906b9272e74f7e7",
          "sha1": "f269cfc699e8919315d694bca04ea7e97911dc22",
          "md5": "3303122805eafcb1326c4883952d924d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "agent-service-interface-1.0.1.jar",
          "url": "agent-service-interface-1.0.1.jar",
          "size": 3285,
          "sha512": "ec4e2b3da84c2970aa13133e12c2e300b7dbb83731df8971a2a9a6656dddffa3a793b86298f6c0126486f9f2110e4c39849e838474d630c7427a59905da3fa36",
          "sha256": "17fa982dc56dd8d4dfb36b43c552957a9479a71ad3f6eff44906b9272e74f7e7",
          "sha1": "f269cfc699e8919315d694bca04ea7e97911dc22",
          "md5": "3303122805eafcb1326c4883952d924d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "agent-service-interface-1.0.1-sources.jar",
          "url": "agent-service-interface-1.0.1-sources.jar",
          "size": 2731,
          "sha512": "806b6df6b955c279bc5f04a638ba56ad3350249c0d552f34e649e6a97578f0dffa4bff895929c9baa07f267990becfc4c7c2b1e8c17b9724edbf268720c58442",
          "sha256": "4660e63752fa8f50e24c9789234803b9db224b0900db9d067d01e92c36c85d43",
          "sha1": "ce41dc5241b228094de586fa21788f31ee21644c",
          "md5": "95b1f3234793356157887037dbcafdfa"
        }
      ]
    }
  ]
}
