{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.17.jar",
          "url": "core-ai-1.1.17.jar",
          "size": 377175,
          "sha512": "e5d82b14ad9a59385a79693a203d1a96f23c89b9d8a942dea9d576183afb21a4978f4adb42237768505a9ee4e15e6535024c9ad9075e3187af03f3e75e5bc048",
          "sha256": "05a326205ad9d2410dd35b59ecedc3af77646cf19c7f11d602da0ca7bb928d44",
          "sha1": "0b16cf6ebe5ecf8ef701b30775d0a78f75451320",
          "md5": "c4a4228cd069597e8ccca5c246fc65b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.17.jar",
          "url": "core-ai-1.1.17.jar",
          "size": 377175,
          "sha512": "e5d82b14ad9a59385a79693a203d1a96f23c89b9d8a942dea9d576183afb21a4978f4adb42237768505a9ee4e15e6535024c9ad9075e3187af03f3e75e5bc048",
          "sha256": "05a326205ad9d2410dd35b59ecedc3af77646cf19c7f11d602da0ca7bb928d44",
          "sha1": "0b16cf6ebe5ecf8ef701b30775d0a78f75451320",
          "md5": "c4a4228cd069597e8ccca5c246fc65b2"
        }
      ]
    }
  ]
}
