{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.69.jar",
          "url": "core-ai-1.1.69.jar",
          "size": 417488,
          "sha512": "8af0e2440af10ca4fa6755f7b4b5fc16ae8871bd07ada640b146f35697594e34545649a043db385fce84f41aac31c35ea71b1407788dc91515625dcc8595ba9d",
          "sha256": "4e960e01d55b5487a29c9b05e4c006fc47467ad2612d43b545b7a8fb9790ccba",
          "sha1": "e154c954fd7a3f33640fbba328276fce737d1522",
          "md5": "b6b41694b4d23d6aab5e176a4c6af08f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.12"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.69.jar",
          "url": "core-ai-1.1.69.jar",
          "size": 417488,
          "sha512": "8af0e2440af10ca4fa6755f7b4b5fc16ae8871bd07ada640b146f35697594e34545649a043db385fce84f41aac31c35ea71b1407788dc91515625dcc8595ba9d",
          "sha256": "4e960e01d55b5487a29c9b05e4c006fc47467ad2612d43b545b7a8fb9790ccba",
          "sha1": "e154c954fd7a3f33640fbba328276fce737d1522",
          "md5": "b6b41694b4d23d6aab5e176a4c6af08f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.69-sources.jar",
          "url": "core-ai-1.1.69-sources.jar",
          "size": 173990,
          "sha512": "050342d64dbd6e76766f4da695f68fc0f808718c4a4bfa719a96aca9757be83101f21ccc066cf3c60be9a7f0929c4893b9d87506b05e67ba377e6a086d3037a9",
          "sha256": "f4d692b21925986e02963a5cedf7a2a43ad8fa93fd86128d7ca3062212ee55d2",
          "sha1": "b3f730101f611ea0f2667398556f0df971a42170",
          "md5": "b7764b0f5a718cf27cc31a92baa47e0d"
        }
      ]
    }
  ]
}
