{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.19.jar",
          "url": "core-ai-1.1.19.jar",
          "size": 377165,
          "sha512": "b6388457af58a190efa35eacb7e0c76aa95611203b515bc374ade9f09da7e3e91e1b95a102737111e545f58e3da87bba7abeb7a79ca0c68971e0e9d000689c48",
          "sha256": "1fc5f8c0f608b24f017b82f6093916fba6e9d079ae382243000114ee2c2d9837",
          "sha1": "b6b6662d4d358a51d07c414a0741e1c63f072fb6",
          "md5": "7b75c840c626dc8a9ebb3e969b476ade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.19.jar",
          "url": "core-ai-1.1.19.jar",
          "size": 377165,
          "sha512": "b6388457af58a190efa35eacb7e0c76aa95611203b515bc374ade9f09da7e3e91e1b95a102737111e545f58e3da87bba7abeb7a79ca0c68971e0e9d000689c48",
          "sha256": "1fc5f8c0f608b24f017b82f6093916fba6e9d079ae382243000114ee2c2d9837",
          "sha1": "b6b6662d4d358a51d07c414a0741e1c63f072fb6",
          "md5": "7b75c840c626dc8a9ebb3e969b476ade"
        }
      ]
    }
  ]
}
