{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.22.jar",
          "url": "core-ai-1.1.22.jar",
          "size": 377465,
          "sha512": "9b542b4da956e942d4d73d183dd594e03aa0102c0bb97547e30b8e8a3d325f72667356b23237219446dcfdf8d4cc660a85af22aa536b01043ce0d13b938fc103",
          "sha256": "db019aeeb4c35395f8eddbadcf59326e1c39b20627d56cf1b8843c3be6181386",
          "sha1": "c8ea70fe0f64fc45f3aa3408d19084a34ff728b2",
          "md5": "a0d80d866fb4f47a30896b02066fdf15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.22.jar",
          "url": "core-ai-1.1.22.jar",
          "size": 377465,
          "sha512": "9b542b4da956e942d4d73d183dd594e03aa0102c0bb97547e30b8e8a3d325f72667356b23237219446dcfdf8d4cc660a85af22aa536b01043ce0d13b938fc103",
          "sha256": "db019aeeb4c35395f8eddbadcf59326e1c39b20627d56cf1b8843c3be6181386",
          "sha1": "c8ea70fe0f64fc45f3aa3408d19084a34ff728b2",
          "md5": "a0d80d866fb4f47a30896b02066fdf15"
        }
      ]
    }
  ]
}
