{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.65.jar",
          "url": "core-ai-1.1.65.jar",
          "size": 386555,
          "sha512": "4c7f549c9f87275f69f79c1ef95baffe793854a02410e8c9a8ee56ea25ab08c36cf3aeb21121e0f3b710fab68062261e5ba0f0d7ae72231e34fe0e653f8cf53d",
          "sha256": "c5efa3cc2ffb76216a3f749337db7da0533b5ff507e8dc2015077948911082ff",
          "sha1": "4c3d6f758aaed70e549c285d9d46185e81293749",
          "md5": "b43a170fae469496023f11871f695051"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.11"
          }
        },
        {
          "group": "com.chancetop",
          "module": "core-ai-mcp",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.65.jar",
          "url": "core-ai-1.1.65.jar",
          "size": 386555,
          "sha512": "4c7f549c9f87275f69f79c1ef95baffe793854a02410e8c9a8ee56ea25ab08c36cf3aeb21121e0f3b710fab68062261e5ba0f0d7ae72231e34fe0e653f8cf53d",
          "sha256": "c5efa3cc2ffb76216a3f749337db7da0533b5ff507e8dc2015077948911082ff",
          "sha1": "4c3d6f758aaed70e549c285d9d46185e81293749",
          "md5": "b43a170fae469496023f11871f695051"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.65-sources.jar",
          "url": "core-ai-1.1.65-sources.jar",
          "size": 160824,
          "sha512": "e77c8588d2a12b4d978fda09617316632563e0ac08b53941fbbaa88c29b0f25f8d8e20c1aabead4f68dc64922e7426758a5c487cc0794619289e9c2b8f920848",
          "sha256": "db40c9ec89957743b4638196e4a58a85464a89b705745a99172f45e12edde4ac",
          "sha1": "eceb919dfd31e2714391b0cfcdc60f639e84b403",
          "md5": "7b6aab4bdf53e98cffb4616f48d6eceb"
        }
      ]
    }
  ]
}
