{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.65.jar",
          "url": "core-ai-1.1.65.jar",
          "size": 410206,
          "sha512": "49677afddcd88e3b974c206c7d5f11bab8d2eb7d335a172a4edf4d7039aa4286b79889f745e2c38e9788231a855c8672bac368993f48bba698b88bca7b7d1d8c",
          "sha256": "b9bbc1e8deaa378bfef73290694d48009eac0bc04b3da7fae12649a8488dd88a",
          "sha1": "1ece8c3db17427868a1418da2c0c9c971e045d41",
          "md5": "a368ecdc3fa4e4cdb5fa80104aa61c4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.11"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.65.jar",
          "url": "core-ai-1.1.65.jar",
          "size": 410206,
          "sha512": "49677afddcd88e3b974c206c7d5f11bab8d2eb7d335a172a4edf4d7039aa4286b79889f745e2c38e9788231a855c8672bac368993f48bba698b88bca7b7d1d8c",
          "sha256": "b9bbc1e8deaa378bfef73290694d48009eac0bc04b3da7fae12649a8488dd88a",
          "sha1": "1ece8c3db17427868a1418da2c0c9c971e045d41",
          "md5": "a368ecdc3fa4e4cdb5fa80104aa61c4a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.65-sources.jar",
          "url": "core-ai-1.1.65-sources.jar",
          "size": 171007,
          "sha512": "9760a02c5af4acaf85abb6c30065c87be8400c56094fbc4a5683440ecca3dfc83e5a05fa5d64f9dff1c0d03278264b4e10902348c1fbffb6d4da910b6509f154",
          "sha256": "90b794b5a380923ead0c42ff64dd7f72ec941b2caa67801816c0e10764f5ad31",
          "sha1": "7a611921241ed2ca4ef0f8d4782a8b6e61f1ed6b",
          "md5": "c78cafb8caf745be2425f19db8f9ab71"
        }
      ]
    }
  ]
}
