{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.102",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.102.jar",
          "url": "core-ai-1.1.102.jar",
          "size": 700863,
          "sha512": "b904514b22bf550e83c94a9434a810631bdeb408e425960e7cdba48d54978e8304e7f259ff1b3b9beb571c85c2a9cc71f53a062f067c35e797875e0803d7365a",
          "sha256": "dc83347c50710acc15eedc690ce4df7e40a87d5afe8e6e7900f926537640d146",
          "sha1": "92f44d5b0627f44799a4c595b54146d7ffc7f84f",
          "md5": "5689fedbcf377886df20bb4d26334532"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.44.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.modelcontextprotocol.sdk",
          "module": "mcp",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.102.jar",
          "url": "core-ai-1.1.102.jar",
          "size": 700863,
          "sha512": "b904514b22bf550e83c94a9434a810631bdeb408e425960e7cdba48d54978e8304e7f259ff1b3b9beb571c85c2a9cc71f53a062f067c35e797875e0803d7365a",
          "sha256": "dc83347c50710acc15eedc690ce4df7e40a87d5afe8e6e7900f926537640d146",
          "sha1": "92f44d5b0627f44799a4c595b54146d7ffc7f84f",
          "md5": "5689fedbcf377886df20bb4d26334532"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.102-sources.jar",
          "url": "core-ai-1.1.102-sources.jar",
          "size": 332831,
          "sha512": "7abfa25bd1508aa56273a771d7ade606a8f00ae81f1f07cf9465491b8afacf58ac32601342c975399e558e7d95ba794e0aa2b8f98c2a0e705825ad0f53f7dbad",
          "sha256": "f47ae42da862cf22b205403091679e327091ee137b4a76f82f4fe4a643350931",
          "sha1": "86157001099c2d9cf25c295e044351e2a8825897",
          "md5": "d7a50f9d8edf70b3c303d1f172596182"
        }
      ]
    }
  ]
}
