{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.27.jar",
          "url": "core-ai-1.1.27.jar",
          "size": 380760,
          "sha512": "7eddb86d3ca5d2397201ce249990fff5b1a01f66b1e3e4209da9bfb3b5965ecb899dfc3a0f1a1986615b8913a16e613b2e272409045816db12b5dd700d058c76",
          "sha256": "e49928ea419d8d4a7b8ef0d28924e618b0c07790121c3c6843cddce2a80c7772",
          "sha1": "d0e93464d38c1d87c7ab4ba699de5389fabdfb38",
          "md5": "45630bf6a4dd0179a8afca9b3223f9b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.27.jar",
          "url": "core-ai-1.1.27.jar",
          "size": 380760,
          "sha512": "7eddb86d3ca5d2397201ce249990fff5b1a01f66b1e3e4209da9bfb3b5965ecb899dfc3a0f1a1986615b8913a16e613b2e272409045816db12b5dd700d058c76",
          "sha256": "e49928ea419d8d4a7b8ef0d28924e618b0c07790121c3c6843cddce2a80c7772",
          "sha1": "d0e93464d38c1d87c7ab4ba699de5389fabdfb38",
          "md5": "45630bf6a4dd0179a8afca9b3223f9b9"
        }
      ]
    }
  ]
}
