{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "language-server-library",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "language-server-library-1.0.0.jar",
          "url": "language-server-library-1.0.0.jar",
          "size": 21979,
          "sha512": "fddb0b925eaff092d886616740e3566ea27215462ca71eea63c7dfdcdb15a78daeda2fa2999ff9a06bd73773af2695be3770715fb7f4d887adb648ca5f41735e",
          "sha256": "4382216f28498efc7375d32d2d345eeba5004eedb7c7c5dcf7eb5b9c2573b031",
          "sha1": "63f21451f2ad4af53a18020e57d69c197abfd3db",
          "md5": "39260afc152d2bd7401756f1cdbb119d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.5"
          }
        },
        {
          "group": "org.eclipse.lsp4j",
          "module": "org.eclipse.lsp4j",
          "version": {
            "requires": "0.23.1"
          }
        }
      ],
      "files": [
        {
          "name": "language-server-library-1.0.0.jar",
          "url": "language-server-library-1.0.0.jar",
          "size": 21979,
          "sha512": "fddb0b925eaff092d886616740e3566ea27215462ca71eea63c7dfdcdb15a78daeda2fa2999ff9a06bd73773af2695be3770715fb7f4d887adb648ca5f41735e",
          "sha256": "4382216f28498efc7375d32d2d345eeba5004eedb7c7c5dcf7eb5b9c2573b031",
          "sha1": "63f21451f2ad4af53a18020e57d69c197abfd3db",
          "md5": "39260afc152d2bd7401756f1cdbb119d"
        }
      ]
    }
  ]
}
