{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.13.jar",
          "url": "core-ai-1.1.13.jar",
          "size": 376937,
          "sha512": "91a8e88f80e1e20140657bcd5cea564e6a049047dfccd588f82105523e08e286cc23be3cb55d5431712ae5d829aa4d373e4c22fe159b5b57006851462b3c0079",
          "sha256": "6b420ff71d5e8cf63d711a3668dbd60a45f7de2a173e03a445f91d50211c6e09",
          "sha1": "91f9618e4720e80424ac28779413048567394e24",
          "md5": "e7cc7a04b18ee5d16bc3c2ea2bd2e84c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.13.jar",
          "url": "core-ai-1.1.13.jar",
          "size": 376937,
          "sha512": "91a8e88f80e1e20140657bcd5cea564e6a049047dfccd588f82105523e08e286cc23be3cb55d5431712ae5d829aa4d373e4c22fe159b5b57006851462b3c0079",
          "sha256": "6b420ff71d5e8cf63d711a3668dbd60a45f7de2a173e03a445f91d50211c6e09",
          "sha1": "91f9618e4720e80424ac28779413048567394e24",
          "md5": "e7cc7a04b18ee5d16bc3c2ea2bd2e84c"
        }
      ]
    }
  ]
}
