{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.81",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.81.jar",
          "url": "core-ai-1.1.81.jar",
          "size": 416947,
          "sha512": "8aaca53708d53bb66e922be21f4b766769b2a53ad4e9536f48b23e79057847475050023dd2e9f9da44015fe00a5397a0252ea05a437dcc3d43e926e0fe90d9a7",
          "sha256": "f879389aa473f00a28e70b3fb2161400ccfd804b381fdadd594b1edfbfa79dc6",
          "sha1": "26d820048ab4535cd73791d1c604656364869cd3",
          "md5": "30f3c15623fea903e1a0ebf54b9d03c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.81.jar",
          "url": "core-ai-1.1.81.jar",
          "size": 416947,
          "sha512": "8aaca53708d53bb66e922be21f4b766769b2a53ad4e9536f48b23e79057847475050023dd2e9f9da44015fe00a5397a0252ea05a437dcc3d43e926e0fe90d9a7",
          "sha256": "f879389aa473f00a28e70b3fb2161400ccfd804b381fdadd594b1edfbfa79dc6",
          "sha1": "26d820048ab4535cd73791d1c604656364869cd3",
          "md5": "30f3c15623fea903e1a0ebf54b9d03c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.81-sources.jar",
          "url": "core-ai-1.1.81-sources.jar",
          "size": 175011,
          "sha512": "b0f84abb4effb7b1ce9d84f1fa8fc71865bf074a4458160763382f34cb381447afacbb450522e379fd02074e627113fae06c5db43b45b9257510f5f80aa2e969",
          "sha256": "eb0aff5c8c818ff93e94619ef8abe8bd2824999d40693aab209fbf73a98b299c",
          "sha1": "92695677fdc4e6742794009c49590bddbf81f228",
          "md5": "3e1269e8eec689d50cf207e2a42d2841"
        }
      ]
    }
  ]
}
