{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.12.jar",
          "url": "core-ai-1.1.12.jar",
          "size": 376324,
          "sha512": "a9cfa66ced9352e1d0233ba21a4da01cd0b4aa15529eb2fe5a40e9c4438a01960514526307cc2f0459880ced8e810c56f83e97b6bc72badd860d41302429a683",
          "sha256": "165b3fb9c53626cfe2f5777b9c66e89f3ce9b6135dee6a03f67d0d645f73b368",
          "sha1": "6b9cb1841c26e708dc781bd6b0e3ef11dd43864e",
          "md5": "eb3d664e8a1b164992f4863ebbf1c915"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.12.jar",
          "url": "core-ai-1.1.12.jar",
          "size": 376324,
          "sha512": "a9cfa66ced9352e1d0233ba21a4da01cd0b4aa15529eb2fe5a40e9c4438a01960514526307cc2f0459880ced8e810c56f83e97b6bc72badd860d41302429a683",
          "sha256": "165b3fb9c53626cfe2f5777b9c66e89f3ce9b6135dee6a03f67d0d645f73b368",
          "sha1": "6b9cb1841c26e708dc781bd6b0e3ef11dd43864e",
          "md5": "eb3d664e8a1b164992f4863ebbf1c915"
        }
      ]
    }
  ]
}
