{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.70.jar",
          "url": "core-ai-1.1.70.jar",
          "size": 417783,
          "sha512": "1c029a7ec6145a4f09096b35a9b77599873a0a31cc3a200bf94db5c53aa5856d923cc07f5c0f63144e2a0ee09f8cb3272f6aa9c926c43e08d79d5b52c8ffacda",
          "sha256": "b9be6d722eb7b5737714bd9545a6103e7379f265c01ab1991b23f443321ee312",
          "sha1": "7220cd2f57844ba687cbb924fdc5ba1eed3401d4",
          "md5": "70c09dd8cf5d7930c3666ce9105376f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.12"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.70.jar",
          "url": "core-ai-1.1.70.jar",
          "size": 417783,
          "sha512": "1c029a7ec6145a4f09096b35a9b77599873a0a31cc3a200bf94db5c53aa5856d923cc07f5c0f63144e2a0ee09f8cb3272f6aa9c926c43e08d79d5b52c8ffacda",
          "sha256": "b9be6d722eb7b5737714bd9545a6103e7379f265c01ab1991b23f443321ee312",
          "sha1": "7220cd2f57844ba687cbb924fdc5ba1eed3401d4",
          "md5": "70c09dd8cf5d7930c3666ce9105376f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.70-sources.jar",
          "url": "core-ai-1.1.70-sources.jar",
          "size": 174080,
          "sha512": "a1b78cbb6ec7f2b1acf72a73c428cc5ada38e1bf73b129e555f27e4ceebb664007325779d12051819da09d11786f779a36b5108b776107801aa280751445e03c",
          "sha256": "9b992c1dbda52deb8bde2da6da620cb0b0e41fea3f93bddeb00c5bec1e0aaa66",
          "sha1": "93a5589ed788005b54d968fbf5febcfc9483e749",
          "md5": "4ac1e7ae9acb81fc246e75d817d65672"
        }
      ]
    }
  ]
}
