{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.15.jar",
          "url": "core-ai-1.1.15.jar",
          "size": 376990,
          "sha512": "ca29f85135d25b7167b9884214f2142659febbb9509814dbe0ad6458540f9b2827b7bfcc06f8b026ff11aad4977bfa3c1cd211c2efdf0829ace230ec928df371",
          "sha256": "e23f75199d70074445fe96c4c432d2c277c3d05c4af93d37af55864685569726",
          "sha1": "c8604a000c2c34e6860df1aeab973e6002851de1",
          "md5": "1df16b19bfdc7c26ed7b5f1bfdd7c4f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.15.jar",
          "url": "core-ai-1.1.15.jar",
          "size": 376990,
          "sha512": "ca29f85135d25b7167b9884214f2142659febbb9509814dbe0ad6458540f9b2827b7bfcc06f8b026ff11aad4977bfa3c1cd211c2efdf0829ace230ec928df371",
          "sha256": "e23f75199d70074445fe96c4c432d2c277c3d05c4af93d37af55864685569726",
          "sha1": "c8604a000c2c34e6860df1aeab973e6002851de1",
          "md5": "1df16b19bfdc7c26ed7b5f1bfdd7c4f5"
        }
      ]
    }
  ]
}
