{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.41.jar",
          "url": "core-ai-1.1.41.jar",
          "size": 381150,
          "sha512": "86e850b7b564c1c2b97f0333b03cbc77fc264730762bc366bad5a5e74bfdab78554273bcc320f01c581b1a1150f8e0b97e336f0ef6597b8d50d2503db99e3937",
          "sha256": "0dba8a3c150d0af506ac00a45bb818c1e881c73c66e319c51f7e2d2e5a628b8b",
          "sha1": "c475375e4a2278bbfda2bc5138c9485e3c1e212e",
          "md5": "7a1978807f161c8d38986d0034668bc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.41.jar",
          "url": "core-ai-1.1.41.jar",
          "size": 381150,
          "sha512": "86e850b7b564c1c2b97f0333b03cbc77fc264730762bc366bad5a5e74bfdab78554273bcc320f01c581b1a1150f8e0b97e336f0ef6597b8d50d2503db99e3937",
          "sha256": "0dba8a3c150d0af506ac00a45bb818c1e881c73c66e319c51f7e2d2e5a628b8b",
          "sha1": "c475375e4a2278bbfda2bc5138c9485e3c1e212e",
          "md5": "7a1978807f161c8d38986d0034668bc9"
        }
      ]
    }
  ]
}
