{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "litellm-library",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litellm-library-1.1.3.jar",
          "url": "litellm-library-1.1.3.jar",
          "size": 27269,
          "sha512": "938ec6a82562425752bafd7328215e5623f4fa846150b635096244e9a859d84c403f2deca16d75a8601345c9afb0263a2c332f3bbd2e94f4204d76df5413064f",
          "sha256": "9d4462c867bc906b6955cd83c5344685fe3a78dc80028e266e639c1f3538e9df",
          "sha1": "27abcb3c8336189aab1200632f0a0cf404c27bcc",
          "md5": "66fb703fdf71f6396a0f064ba47792cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "litellm-library-1.1.3.jar",
          "url": "litellm-library-1.1.3.jar",
          "size": 27269,
          "sha512": "938ec6a82562425752bafd7328215e5623f4fa846150b635096244e9a859d84c403f2deca16d75a8601345c9afb0263a2c332f3bbd2e94f4204d76df5413064f",
          "sha256": "9d4462c867bc906b6955cd83c5344685fe3a78dc80028e266e639c1f3538e9df",
          "sha1": "27abcb3c8336189aab1200632f0a0cf404c27bcc",
          "md5": "66fb703fdf71f6396a0f064ba47792cf"
        }
      ]
    }
  ]
}
