{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.64.jar",
          "url": "core-ai-1.1.64.jar",
          "size": 377451,
          "sha512": "1707de824b6a8afe8768bdd707993c5c5b88a82f5a467136ed975b46b09edd07c2e1060b38f33eff0ff459d2473268ed76d40ed30a506830074545064f7d4893",
          "sha256": "dccccec3868e3ad88ec37f29a51e2f0774428d9e7efa9c3b980122aeee6728f1",
          "sha1": "3aa3cad4e47b5fcf71795bbbc5360028aee1e15a",
          "md5": "1af2d47a51f7472b7eaacc64dfe7bdc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.11"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.64.jar",
          "url": "core-ai-1.1.64.jar",
          "size": 377451,
          "sha512": "1707de824b6a8afe8768bdd707993c5c5b88a82f5a467136ed975b46b09edd07c2e1060b38f33eff0ff459d2473268ed76d40ed30a506830074545064f7d4893",
          "sha256": "dccccec3868e3ad88ec37f29a51e2f0774428d9e7efa9c3b980122aeee6728f1",
          "sha1": "3aa3cad4e47b5fcf71795bbbc5360028aee1e15a",
          "md5": "1af2d47a51f7472b7eaacc64dfe7bdc2"
        }
      ]
    }
  ]
}
