{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.34.jar",
          "url": "core-ai-1.1.34.jar",
          "size": 381029,
          "sha512": "8ee51bff39a163fc3a1b3c352bcb5082de399cdac24df2d805ec78cf57b4321fc7353815ef4da049bc644f48582616bbd448c843708c075614805aec2a039da2",
          "sha256": "0f129f2b3c0105172188681a1b1e6fb3299764794e857c710422389ab672f16e",
          "sha1": "fe400ced3658b2912f0a7058dc092b268d922843",
          "md5": "f975d3a60b1bcb922306c5f43037d83c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.34.jar",
          "url": "core-ai-1.1.34.jar",
          "size": 381029,
          "sha512": "8ee51bff39a163fc3a1b3c352bcb5082de399cdac24df2d805ec78cf57b4321fc7353815ef4da049bc644f48582616bbd448c843708c075614805aec2a039da2",
          "sha256": "0f129f2b3c0105172188681a1b1e6fb3299764794e857c710422389ab672f16e",
          "sha1": "fe400ced3658b2912f0a7058dc092b268d922843",
          "md5": "f975d3a60b1bcb922306c5f43037d83c"
        }
      ]
    }
  ]
}
