{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.82",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.82.jar",
          "url": "core-ai-1.1.82.jar",
          "size": 417499,
          "sha512": "e27a4d77cb1e2919005157bfc9da23388a807ea0207052632ab15323a4489120f51cd663e01a1ba927370fe3a4fac3eef3887ed52c6585977479965f50d656bb",
          "sha256": "2e71af1745de442f0e58dbb0b42bdb8344ba4d34af9b5f79b4302bd442f42f91",
          "sha1": "ccf4ac7aa7cf0dff8e29910c5e106488c5be3a18",
          "md5": "3698c8d41c736891670966448fb69edd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.16"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.5"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.82.jar",
          "url": "core-ai-1.1.82.jar",
          "size": 417499,
          "sha512": "e27a4d77cb1e2919005157bfc9da23388a807ea0207052632ab15323a4489120f51cd663e01a1ba927370fe3a4fac3eef3887ed52c6585977479965f50d656bb",
          "sha256": "2e71af1745de442f0e58dbb0b42bdb8344ba4d34af9b5f79b4302bd442f42f91",
          "sha1": "ccf4ac7aa7cf0dff8e29910c5e106488c5be3a18",
          "md5": "3698c8d41c736891670966448fb69edd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-1.1.82-sources.jar",
          "url": "core-ai-1.1.82-sources.jar",
          "size": 175213,
          "sha512": "97e0db7166016a59eb44deac9f72f109a005f94fb4522cc1aee94e27616eb027b744357ec4c42431bd34d1492978088dfae4e086e98f878db694588c36bad98a",
          "sha256": "3d4ddac1690efb81c56e5ee22d7e5138a8adb826d247f612ff82123c5245c908",
          "sha1": "68619df7f59d3c89644f9a5a1b2dddc406a651b4",
          "md5": "7ae5c44271f856583eb0bdfc08f25971"
        }
      ]
    }
  ]
}
