{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai-api",
    "version": "1.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.14.jar",
          "url": "core-ai-api-1.1.14.jar",
          "size": 39080,
          "sha512": "917f9233566e30977237cbebfb29c272fe9ded7c5558bea6398a65d0a0b2e651c271a38b736a9a2142bd77829905e9b8cd48cde0e61dbc4a0a71e16f1be0c4e2",
          "sha256": "6b5af1cb5f26db7caa40123a134a67197ede762a5b7bef61d3e35d4d02a63151",
          "sha1": "54cd891a87ba49ec484f1cb0e42ca09e47a0354e",
          "md5": "249fa4febba46c04f97e45df2fc3c1e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-api-1.1.14.jar",
          "url": "core-ai-api-1.1.14.jar",
          "size": 39080,
          "sha512": "917f9233566e30977237cbebfb29c272fe9ded7c5558bea6398a65d0a0b2e651c271a38b736a9a2142bd77829905e9b8cd48cde0e61dbc4a0a71e16f1be0c4e2",
          "sha256": "6b5af1cb5f26db7caa40123a134a67197ede762a5b7bef61d3e35d4d02a63151",
          "sha1": "54cd891a87ba49ec484f1cb0e42ca09e47a0354e",
          "md5": "249fa4febba46c04f97e45df2fc3c1e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ai-api-1.1.14-sources.jar",
          "url": "core-ai-api-1.1.14-sources.jar",
          "size": 22483,
          "sha512": "5e8567a462f700d024656a4f6efa460a02cf76a143d35f3812a82eb800666e01f4b0fd9c2f2d036d71a40a6dcef66b9273ac46f2dcbb0fa0908b8af79e574bf1",
          "sha256": "d816ff33c211dd4cf32601a35a1ad45c860a0462c1ec8649a2833b18d7de8178",
          "sha1": "baa36dfb1d20e79941b67e0a897c377f43bb3958",
          "md5": "17d60a1cbde3eac0f7ccbf0bc3a0d3a0"
        }
      ]
    }
  ]
}
