{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.51.jar",
          "url": "core-ai-1.1.51.jar",
          "size": 385997,
          "sha512": "6e8ea16afbf79c5cb8e335351ae56d84c7f55b22e1203b4992bb14cbed958f3cc7e4f6fdf85a67bbcec961a95a56fd80dc69813989b980add011e44bf2f324b1",
          "sha256": "d66f1c81f844807eb5c69c64040deeea6373ba6c1a7a83b160d11786e73cf0e6",
          "sha1": "c0b7d4d4322c8d43362077a1c972e45259a9d12b",
          "md5": "cbf6fa032e6b347243391a1b01c125a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.11"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.51.jar",
          "url": "core-ai-1.1.51.jar",
          "size": 385997,
          "sha512": "6e8ea16afbf79c5cb8e335351ae56d84c7f55b22e1203b4992bb14cbed958f3cc7e4f6fdf85a67bbcec961a95a56fd80dc69813989b980add011e44bf2f324b1",
          "sha256": "d66f1c81f844807eb5c69c64040deeea6373ba6c1a7a83b160d11786e73cf0e6",
          "sha1": "c0b7d4d4322c8d43362077a1c972e45259a9d12b",
          "md5": "cbf6fa032e6b347243391a1b01c125a9"
        }
      ]
    }
  ]
}
