{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chancetop",
    "module": "core-ai",
    "version": "1.1.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ai-1.1.40.jar",
          "url": "core-ai-1.1.40.jar",
          "size": 381263,
          "sha512": "798a22036188a3f90f26192523d8c1eb6c1c3b6564a689e77bf438526572e9736b7750a6b30cbed76cea0fd762b4bb1404c2c8886a6989e63a8ee974e21c5efe",
          "sha256": "94ae238b3903fb157ebd85473a72baefc18b4cc0eb4403782d5bcde1cc0271e3",
          "sha1": "61c0c5467868346c1ce8b7808ed2ee57d358d143",
          "md5": "656b1929d05b5a7f9f77953f3bdd41a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.chancetop",
          "module": "core-ai-api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.chancetop",
          "module": "litellm-library",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-openai",
          "version": {
            "requires": "1.0.0-beta.12"
          }
        },
        {
          "group": "com.azure",
          "module": "azure-ai-inference",
          "version": {
            "requires": "1.0.0-beta.4"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.10"
          }
        },
        {
          "group": "io.milvus",
          "module": "milvus-sdk-java",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.jelmerk",
          "module": "hnswlib-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.knuddels",
          "module": "jtokkit",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ai-1.1.40.jar",
          "url": "core-ai-1.1.40.jar",
          "size": 381263,
          "sha512": "798a22036188a3f90f26192523d8c1eb6c1c3b6564a689e77bf438526572e9736b7750a6b30cbed76cea0fd762b4bb1404c2c8886a6989e63a8ee974e21c5efe",
          "sha256": "94ae238b3903fb157ebd85473a72baefc18b4cc0eb4403782d5bcde1cc0271e3",
          "sha1": "61c0c5467868346c1ce8b7808ed2ee57d358d143",
          "md5": "656b1929d05b5a7f9f77953f3bdd41a6"
        }
      ]
    }
  ]
}
